// One sidebar over the developer documentation tree in ../docs.
//
// Labels live here rather than in _category_.json files so that the normative
// documentation tree stays free of site-generator metadata. Order follows the
// constitutional authority chain: INV-CORE -> INV-ARC -> DOM -> FEAT.

const category = (label, dirName, description) => ({
  type: "category",
  label,
  link: {
    type: "generated-index",
    title: label,
    description,
  },
  items: [{type: "autogenerated", dirName}],
});

module.exports = {
  developer: [
    category(
      "Invariants",
      "INVARIANT",
      "Constitutional authority. INV-CORE documents are foundational; INV-ARC documents govern architecture. Nothing below this tier may contradict them.",
    ),
    category(
      "Domain Authority",
      "DOMAIN",
      "Per-domain authority specs (DOM-*). These define what each domain owns and the contracts it exposes.",
    ),
    category(
      "Feature Execution",
      "FEATURE-EXECUTION",
      "FEAT contracts. Every state mutation in the application runs through one of these.",
    ),
    category(
      "Specifications",
      "SPEC",
      "Technical contracts (SPEC-*) covering testing, design system, time handling, and build requirements.",
    ),
    category(
      "Standard Operating Procedures",
      "STANDARD_OPERATING_PROCEDURES",
      "SOP-* procedures for database migrations, deployment, devops, and documentation.",
    ),
    category(
      "Interface Maps",
      "MAP",
      "Domain-to-FEAT capability maps and UI wiring specifications.",
    ),
    category(
      "Reference",
      "REFERENCE",
      "Authoritative vocabulary and interface references (REF-*).",
    ),
    category(
      "Principles",
      "PRINCIPLES",
      "PRN-* rationale: why a design was chosen. Informative, not binding.",
    ),
    category(
      "Operations",
      "ops",
      "Operational notes, audits, and evidence.",
    ),
    category(
      "Self-Hosting",
      "self-hosting",
      "Running your own instance of Classroom Token Hub.",
    ),
    category(
      "Tracking",
      "TRACKING",
      "Launch readiness, domain progress, and migration status. Descriptive, never authoritative.",
    ),
  ],
};
