import hmac
import os
import secrets
from hashlib import sha256

from werkzeug.security import check_password_hash, generate_password_hash


def _get_pepper() -> bytes:
    """Return the primary pepper as bytes."""

    value = os.environ.get("PEPPER_KEY")
    if not value:
        raise KeyError("PEPPER_KEY")
    return value.encode()


def hash_hmac(value: bytes, salt: bytes) -> str:
    """Return HMAC-SHA256 hex digest of ``salt + value`` using the primary pepper."""

    pepper = _get_pepper()
    return hmac.new(pepper, salt + value, sha256).hexdigest()


def hash_username(username: str, salt: bytes) -> str:
    return hash_hmac(username.encode(), salt)


def hash_username_lookup(username: str) -> str:
    """Return a deterministic HMAC hash for username lookups.

    This intentionally omits the per-user salt so we can query by username
    without scanning all stored salts. It still relies on the global pepper
    for secrecy.
    """

    pepper = _get_pepper()
    return hmac.new(pepper, username.encode(), sha256).hexdigest()


def get_random_salt() -> bytes:
    """Return 16 cryptographically secure random bytes."""

    return secrets.token_bytes(16)


#: The canonical password KDF profile, fixed by SPEC-SEC-001 §V.1.2 and binding
#: through INV-ARC-019 §VI. It is written out rather than left to Werkzeug's
#: default even though the default currently matches, because a default that
#: happens to agree with a specification is a coincidence a dependency upgrade
#: may end silently — and the resulting drift would be invisible: new hashes
#: would simply be minted under different parameters while every existing hash
#: kept verifying, since the encoded verifier carries its own parameters.
#: SPEC-SEC-001 §VII prohibits substituting parameters, so changing this
#: constant requires a revision of that specification first.
PASSWORD_KDF = "scrypt:32768:8:1"


def hash_password(value: str) -> str:
    """Hash a credential for storage.

    Named seam over the password KDF so call sites do not bind to a specific
    algorithm — SPEC-SEC-001 §V.1.5 requires the algorithm and its parameters to
    live in one primitive rather than being duplicated at call sites. scrypt is
    memory-hard, and the random per-hash salt is generated by Werkzeug and
    embedded in the returned verifier string (§V.1.2).

    Credentials are deliberately NOT peppered. `PEPPER_KEY` is scoped to keyed
    HMAC lookup digests (INV-ARC-018 §V.1) and is prohibited as an input here by
    SPEC-SEC-001 §V.1.3. Peppering credentials would couple every password to a
    key whose rotation is already a lookup-digest migration event, silently
    converting it into a credential-invalidating one; INV-ARC-019 §VI records
    that reasoning as settled.

    Used for `User.pin_hash`, `User.passphrase_hash`, and
    `StudentRecoveryCode.code_hash`.
    """

    return generate_password_hash(value, method=PASSWORD_KDF)


def verify_password(value: str, stored_hash: str) -> bool:
    """Verify a plaintext credential against a stored hash.

    Argument order is (plaintext, stored_hash) — the reverse of Werkzeug's.

    Returns False for every unusable verifier without distinguishing which
    condition occurred, per SPEC-SEC-001 §V.1.6. Werkzeug is only partly
    fail-closed here: `check_password_hash` catches the `ValueError` from
    splitting a verifier that has too few `$`-separated fields, but a verifier
    that splits into three fields with an unrecognized or empty method reaches
    `_hash_internal`, which raises `ValueError("Invalid hash method ...")`. That
    exception would escape into the login handler and become a 500, which
    distinguishes "this account's stored verifier is damaged" from "wrong
    passphrase" by response code alone — the disclosure §V.1.6 prohibits. A
    damaged verifier is also exactly what a partially completed credential
    migration leaves behind, so this is a reachable state, not a theoretical
    one.
    """

    if not stored_hash or not value:
        return False

    try:
        return check_password_hash(stored_hash, value)
    except (ValueError, TypeError):
        return False
