import hmac
import json
import unicodedata
import os
import secrets
from hashlib import sha256

from werkzeug.security import check_password_hash, generate_password_hash


def _get_pepper() -> bytes:
    """Return the primary pepper as bytes."""

    value = os.environ.get("PEPPER_KEY")
    if not value:
        raise KeyError("PEPPER_KEY")
    return value.encode()


def hash_hmac(value: bytes, salt: bytes) -> str:
    """Return HMAC-SHA256 hex digest of ``salt + value`` using the primary pepper."""

    pepper = _get_pepper()
    return hmac.new(pepper, salt + value, sha256).hexdigest()


def normalize_lookup_text(value: str, *, kind: str) -> str:
    """SPEC-SEC-001 V.2: NFKC, trim edges; names additionally lowercase.

    Internal whitespace and punctuation remain significant. Usernames retain
    case sensitivity. Scope IDs and opaque codes never use name normalization.
    """
    if not isinstance(value, str):
        raise TypeError("Lookup text must be a string")
    if kind not in {"username", "name"}:
        raise ValueError("Unknown lookup normalization kind")
    normalized = unicodedata.normalize("NFKC", value).strip()
    return normalized.lower() if kind == "name" else normalized


def _lookup_digest(label: str, *parts: str) -> str:
    # Structured framing keeps user-controlled delimiters out of field boundaries.
    payload = json.dumps(["cth.identity.lookup.v1", label, *parts],
                         ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    return hmac.new(_get_pepper(), payload, sha256).hexdigest()


def hash_username(username: str, salt: bytes) -> str:
    return _lookup_digest("username-verifier", salt.hex(),
                          normalize_lookup_text(username, kind="username"))


def hash_username_lookup(username: str) -> str:
    """Global principal lookup; deliberately independent of class authority."""
    return _lookup_digest("username", normalize_lookup_text(username, kind="username"))


def hash_claim_name(value: str, *, class_id: str, field: str) -> str:
    if not isinstance(class_id, str) or not class_id.strip():
        raise ValueError("Canonical class_id is required")
    if field not in {"first", "last"}:
        raise ValueError("Unknown claim name field")
    return _lookup_digest("claim-" + field + "-name", class_id,
                          normalize_lookup_text(value, kind="name"))


def hash_roster_fingerprint(*, class_id: str, first_name: str,
                            last_name: str, dedupe_code: str = "") -> str:
    if not isinstance(class_id, str) or not class_id.strip():
        raise ValueError("Canonical class_id is required")
    return _lookup_digest("roster-fingerprint", class_id,
        normalize_lookup_text(first_name, kind="name"),
        normalize_lookup_text(last_name, kind="name"), dedupe_code.strip().upper())


def get_random_salt() -> bytes:
    """Return 16 cryptographically secure random bytes."""

    return secrets.token_bytes(16)


#: The canonical password KDF profile, fixed by SPEC-SEC-001 §V.1.2 and binding
#: through INV-ARC-019 §VI. It is written out rather than left to Werkzeug's
#: default even though the default currently matches, because a default that
#: happens to agree with a specification is a coincidence a dependency upgrade
#: may end silently — and the resulting drift would be invisible: new hashes
#: would simply be minted under different parameters while every existing hash
#: kept verifying, since the encoded verifier carries its own parameters.
#: SPEC-SEC-001 §VII prohibits substituting parameters, so changing this
#: constant requires a revision of that specification first.
PASSWORD_KDF = "scrypt:32768:8:1"


def hash_password(value: str) -> str:
    """Hash a credential for storage.

    Named seam over the password KDF so call sites do not bind to a specific
    algorithm — SPEC-SEC-001 §V.1.5 requires the algorithm and its parameters to
    live in one primitive rather than being duplicated at call sites. scrypt is
    memory-hard, and the random per-hash salt is generated by Werkzeug and
    embedded in the returned verifier string (§V.1.2).

    Credentials are deliberately NOT peppered. `PEPPER_KEY` is scoped to keyed
    HMAC lookup digests (INV-ARC-018 §V.1) and is prohibited as an input here by
    SPEC-SEC-001 §V.1.3. Peppering credentials would couple every password to a
    key whose rotation is already a lookup-digest migration event, silently
    converting it into a credential-invalidating one; INV-ARC-019 §VI records
    that reasoning as settled.

    Used for `User.pin_hash`, `User.passphrase_hash`, and
    `StudentRecoveryCode.code_hash`.
    """

    return generate_password_hash(value, method=PASSWORD_KDF)


def verify_password(value: str, stored_hash: str) -> bool:
    """Verify a plaintext credential against a stored hash.

    Argument order is (plaintext, stored_hash) — the reverse of Werkzeug's.

    Returns False for every unusable verifier without distinguishing which
    condition occurred, per SPEC-SEC-001 §V.1.6. Werkzeug is only partly
    fail-closed here: `check_password_hash` catches the `ValueError` from
    splitting a verifier that has too few `$`-separated fields, but a verifier
    that splits into three fields with an unrecognized or empty method reaches
    `_hash_internal`, which raises `ValueError("Invalid hash method ...")`. That
    exception would escape into the login handler and become a 500, which
    distinguishes "this account's stored verifier is damaged" from "wrong
    passphrase" by response code alone — the disclosure §V.1.6 prohibits. A
    damaged verifier is also exactly what a partially completed credential
    migration leaves behind, so this is a reachable state, not a theoretical
    one.
    """

    if not stored_hash or not value:
        return False

    try:
        return check_password_hash(stored_hash, value)
    except (ValueError, TypeError):
        return False
