"""add teacher analytics

Revision ID: 1a4ee2388d62
Revises: h7i8j9k0l1m2
Create Date: 2026-01-06 21:49:10.009711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1a4ee2388d62'
down_revision = 'h7i8j9k0l1m2'
branch_labels = None
depends_on = None

# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def constraint_exists(table_name, constraint_name, constraint_type='unique'):
    """Check if a constraint exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        if constraint_type == 'unique':
            constraints = [uc['name'] for uc in inspector.get_unique_constraints(table_name)]
        elif constraint_type == 'foreignkey':
            constraints = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        else:
            return False
        return constraint_name in constraints
    except Exception:
        return False

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('analytics_alerts'):
        op.create_table('analytics_alerts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('join_code', sa.String(length=20), nullable=False),
        sa.Column('alert_type', sa.String(length=50), nullable=False),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('what_changed', sa.String(length=255), nullable=False),
        sa.Column('why_it_matters', sa.Text(), nullable=False),
        sa.Column('suggested_action', sa.Text(), nullable=True),
        sa.Column('metric_name', sa.String(length=100), nullable=True),
        sa.Column('current_value', sa.Float(), nullable=True),
        sa.Column('threshold_value', sa.Float(), nullable=True),
        sa.Column('triggered_at', sa.DateTime(), nullable=False),
        sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
        sa.Column('resolved_at', sa.DateTime(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    else:
        # Table exists but might be missing columns from a partial/failed migration
        with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
            if not column_exists('analytics_alerts', 'teacher_id'):
                batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True)) # Nullable first for safety
            if not column_exists('analytics_alerts', 'alert_type'):
                batch_op.add_column(sa.Column('alert_type', sa.String(length=50), nullable=True))
            if not column_exists('analytics_alerts', 'metric_name'):
                batch_op.add_column(sa.Column('metric_name', sa.String(length=100), nullable=True))
            if not column_exists('analytics_alerts', 'current_value'):
                batch_op.add_column(sa.Column('current_value', sa.Float(), nullable=True))
            if not column_exists('analytics_alerts', 'threshold_value'):
                batch_op.add_column(sa.Column('threshold_value', sa.Float(), nullable=True))
            if not column_exists('analytics_alerts', 'triggered_at'):
                batch_op.add_column(sa.Column('triggered_at', sa.DateTime(), nullable=True))
            if not column_exists('analytics_alerts', 'is_active'):
                batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default='true'))

    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        if not index_exists('analytics_alerts', 'ix_analytics_alerts_join_code'):
            batch_op.create_index(batch_op.f('ix_analytics_alerts_join_code'), ['join_code'], unique=False)
        if not index_exists('analytics_alerts', 'ix_analytics_alerts_join_code_active'):
            batch_op.create_index('ix_analytics_alerts_join_code_active', ['join_code', 'is_active'], unique=False)
        if not index_exists('analytics_alerts', 'ix_analytics_alerts_severity'):
            batch_op.create_index('ix_analytics_alerts_severity', ['severity', 'is_active'], unique=False)
        if not index_exists('analytics_alerts', 'ix_analytics_alerts_teacher_active'):
            batch_op.create_index('ix_analytics_alerts_teacher_active', ['teacher_id', 'is_active'], unique=False)
        if not index_exists('analytics_alerts', 'ix_analytics_alerts_triggered'):
            batch_op.create_index('ix_analytics_alerts_triggered', ['triggered_at'], unique=False)

    if not table_exists('analytics_events'):
        op.create_table('analytics_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('join_code', sa.String(length=20), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('event_date', sa.DateTime(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=False),
        sa.Column('old_value', sa.Float(), nullable=True),
        sa.Column('new_value', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('created_by_admin', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        if not index_exists('analytics_events', 'ix_analytics_events_join_code'):
            batch_op.create_index(batch_op.f('ix_analytics_events_join_code'), ['join_code'], unique=False)
        if not index_exists('analytics_events', 'ix_analytics_events_join_code_date'):
            batch_op.create_index('ix_analytics_events_join_code_date', ['join_code', 'event_date'], unique=False)
        if not index_exists('analytics_events', 'ix_analytics_events_teacher_date'):
            batch_op.create_index('ix_analytics_events_teacher_date', ['teacher_id', 'event_date'], unique=False)
        if not index_exists('analytics_events', 'ix_analytics_events_type'):
            batch_op.create_index('ix_analytics_events_type', ['event_type'], unique=False)

    if not table_exists('analytics_snapshots'):
        op.create_table('analytics_snapshots',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('teacher_id', sa.Integer(), nullable=False),
        sa.Column('join_code', sa.String(length=20), nullable=False),
        sa.Column('window_type', sa.String(length=20), nullable=False),
        sa.Column('window_start', sa.DateTime(), nullable=False),
        sa.Column('window_end', sa.DateTime(), nullable=False),
        sa.Column('participation_rate', sa.Float(), nullable=True),
        sa.Column('money_velocity', sa.Float(), nullable=True),
        sa.Column('cwi_deviation_within_20pct', sa.Float(), nullable=True),
        sa.Column('budget_survival_pass_rate', sa.Float(), nullable=True),
        sa.Column('cwi_value', sa.Float(), nullable=False),
        sa.Column('avg_student_balance', sa.Float(), nullable=True),
        sa.Column('balance_trend', sa.String(length=20), nullable=True),
        sa.Column('velocity_trend', sa.String(length=20), nullable=True),
        sa.Column('participation_trend', sa.String(length=20), nullable=True),
        sa.Column('total_students', sa.Integer(), nullable=False),
        sa.Column('active_students', sa.Integer(), nullable=True),
        sa.Column('total_transactions', sa.Integer(), nullable=True),
        sa.Column('computed_at', sa.DateTime(), nullable=False),
        sa.Column('is_complete', sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        if not index_exists('analytics_snapshots', 'ix_analytics_computed_at'):
            batch_op.create_index('ix_analytics_computed_at', ['computed_at'], unique=False)
        if not index_exists('analytics_snapshots', 'ix_analytics_join_code_window'):
            batch_op.create_index('ix_analytics_join_code_window', ['join_code', 'window_type', 'window_start'], unique=False)
        if not index_exists('analytics_snapshots', 'ix_analytics_snapshots_join_code'):
            batch_op.create_index(batch_op.f('ix_analytics_snapshots_join_code'), ['join_code'], unique=False)
        if not index_exists('analytics_snapshots', 'ix_analytics_teacher_window'):
            batch_op.create_index('ix_analytics_teacher_window', ['teacher_id', 'window_type', 'window_start'], unique=False)

    # Conditionally drop index and columns from admin_credentials if they exist
    # These may not exist depending on which migration path was taken
    if table_exists('admin_credentials'):
        with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
            if index_exists('admin_credentials', 'ix_admin_credentials_credential_id'):
                batch_op.drop_index(batch_op.f('ix_admin_credentials_credential_id'))
            if column_exists('admin_credentials', 'public_key'):
                batch_op.drop_column('public_key')
            if column_exists('admin_credentials', 'aaguid'):
                batch_op.drop_column('aaguid')
            if column_exists('admin_credentials', 'sign_count'):
                batch_op.drop_column('sign_count')
            if column_exists('admin_credentials', 'transports'):
                batch_op.drop_column('transports')

    if table_exists('banking_settings'):
        with op.batch_alter_table('banking_settings', schema=None) as batch_op:
            batch_op.alter_column('teacher_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
            if not index_exists('banking_settings', 'ix_banking_settings_teacher_id'):
                batch_op.create_index(batch_op.f('ix_banking_settings_teacher_id'), ['teacher_id'], unique=False)

    if table_exists('hall_pass_logs'):
        with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
            if index_exists('hall_pass_logs', 'ix_hall_pass_logs_student_join_code'):
                batch_op.drop_index(batch_op.f('ix_hall_pass_logs_student_join_code'))

    if table_exists('hall_pass_settings'):
        with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
            batch_op.alter_column('teacher_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
            if not index_exists('hall_pass_settings', 'ix_hall_pass_settings_teacher_id'):
                batch_op.create_index(batch_op.f('ix_hall_pass_settings_teacher_id'), ['teacher_id'], unique=False)

    if table_exists('insurance_policies'):
        with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
            batch_op.alter_column('policy_code',
                   existing_type=sa.VARCHAR(length=16),
                   nullable=False)
            batch_op.alter_column('is_monetary',
                   existing_type=sa.BOOLEAN(),
                   nullable=True)
            batch_op.alter_column('enable_repurchase_cooldown',
                   existing_type=sa.BOOLEAN(),
                   nullable=True)
            batch_op.alter_column('bundle_discount_amount',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=True)
            if constraint_exists('insurance_policies', 'uq_insurance_policies_policy_code', 'unique'):
                batch_op.drop_constraint(batch_op.f('uq_insurance_policies_policy_code'), type_='unique')
            if index_exists('insurance_policies', 'ix_insurance_policies_policy_code'):
                batch_op.drop_index(batch_op.f('ix_insurance_policies_policy_code'))
            # Only create the index if it doesn't already exist (unique index)
            if not index_exists('insurance_policies', 'ix_insurance_policies_policy_code'):
                batch_op.create_index(batch_op.f('ix_insurance_policies_policy_code'), ['policy_code'], unique=True)
            if constraint_exists('insurance_policies', 'fk_insurance_policies_teacher_id', 'foreignkey'):
                batch_op.drop_constraint(batch_op.f('fk_insurance_policies_teacher_id'), type_='foreignkey')

    if table_exists('payroll_fines'):
        with op.batch_alter_table('payroll_fines', schema=None) as batch_op:
            batch_op.alter_column('teacher_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    if table_exists('payroll_rewards'):
        with op.batch_alter_table('payroll_rewards', schema=None) as batch_op:
            batch_op.alter_column('teacher_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    if table_exists('payroll_settings'):
        with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
            batch_op.alter_column('teacher_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)
            if not index_exists('payroll_settings', 'ix_payroll_settings_teacher_id'):
                batch_op.create_index(batch_op.f('ix_payroll_settings_teacher_id'), ['teacher_id'], unique=False)

    if table_exists('rent_items'):
        with op.batch_alter_table('rent_items', schema=None) as batch_op:
            batch_op.alter_column('store_price',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   type_=sa.Numeric(precision=10, scale=2),
                   existing_nullable=True)

    if table_exists('rent_payments'):
        with op.batch_alter_table('rent_payments', schema=None) as batch_op:
            if index_exists('rent_payments', 'ix_rent_payments_student_join_code'):
                batch_op.drop_index(batch_op.f('ix_rent_payments_student_join_code'))

    # Backfill rent_settings.teacher_id before enforcing NOT NULL to avoid failures on legacy rows
    bind = op.get_bind()
    if table_exists('rent_settings'):
        try:
            null_count = bind.execute(sa.text("SELECT COUNT(*) FROM rent_settings WHERE teacher_id IS NULL")).scalar()
        except Exception:
            null_count = 0
    
        if null_count:
            # Prefer any existing admin as the owning teacher; choose the smallest id for determinism
            admin_id = bind.execute(sa.text("SELECT MIN(id) FROM admins")).scalar()
            if admin_id is not None:
                bind.execute(sa.text("UPDATE rent_settings SET teacher_id = :aid WHERE teacher_id IS NULL"), {"aid": admin_id})
    
        with op.batch_alter_table('rent_settings', schema=None) as batch_op:
            # Only set NOT NULL if no NULLs remain after backfill; otherwise keep nullable to avoid breaking upgrades
            try:
                remaining = bind.execute(sa.text("SELECT COUNT(*) FROM rent_settings WHERE teacher_id IS NULL")).scalar()
            except Exception:
                remaining = 0
            if not remaining:
                batch_op.alter_column('teacher_id',
                       existing_type=sa.INTEGER(),
                       nullable=False)
            batch_op.alter_column('frequency_type',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True,
                   existing_server_default=sa.text("'monthly'::character varying"))
            batch_op.alter_column('late_penalty_amount',
                   existing_type=sa.DOUBLE_PRECISION(precision=53),
                   nullable=True,
                   existing_server_default=sa.text("'10'::double precision"))
            batch_op.alter_column('late_penalty_type',
                   existing_type=sa.VARCHAR(length=20),
                   nullable=True,
                   existing_server_default=sa.text("'once'::character varying"))
            batch_op.alter_column('bill_preview_enabled',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
            batch_op.alter_column('bill_preview_days',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   existing_server_default=sa.text('7'))
            batch_op.alter_column('allow_incremental_payment',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
            batch_op.alter_column('prevent_purchase_when_late',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
            if not index_exists('rent_settings', 'ix_rent_settings_teacher_id'):
                batch_op.create_index(batch_op.f('ix_rent_settings_teacher_id'), ['teacher_id'], unique=False)
            if column_exists('rent_settings', 'late_fee'):
                batch_op.drop_column('late_fee')

    if table_exists('store_items'):
        with op.batch_alter_table('store_items', schema=None) as batch_op:
            batch_op.alter_column('teacher_id',
                   existing_type=sa.INTEGER(),
                   nullable=False)

    if table_exists('student_insurance'):
        with op.batch_alter_table('student_insurance', schema=None) as batch_op:
            if index_exists('student_insurance', 'ix_student_insurance_student_join_code'):
                batch_op.drop_index(batch_op.f('ix_student_insurance_student_join_code'))

    if table_exists('student_items'):
        with op.batch_alter_table('student_items', schema=None) as batch_op:
            if index_exists('student_items', 'ix_student_items_student_join_code'):
                batch_op.drop_index(batch_op.f('ix_student_items_student_join_code'))

    if table_exists('student_recovery_codes'):
        with op.batch_alter_table('student_recovery_codes', schema=None) as batch_op:
            if constraint_exists('student_recovery_codes', 'student_recovery_codes_recovery_request_id_fkey', 'foreignkey'):
                batch_op.drop_constraint(batch_op.f('student_recovery_codes_recovery_request_id_fkey'), type_='foreignkey')
                batch_op.create_foreign_key(None, 'recovery_requests', ['recovery_request_id'], ['id'])

    if table_exists('students'):
        with op.batch_alter_table('students', schema=None) as batch_op:
            batch_op.alter_column('has_completed_profile_migration',
                   existing_type=sa.BOOLEAN(),
                   nullable=True,
                   existing_server_default=sa.text('false'))
            if index_exists('students', 'ix_students_teacher_id'):
                batch_op.drop_index(batch_op.f('ix_students_teacher_id'))

    # Conditionally drop index and columns from system_admin_credentials if they exist
    if table_exists('system_admin_credentials'):
        with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
            if index_exists('system_admin_credentials', 'ix_system_admin_credentials_credential_id'):
                batch_op.drop_index(batch_op.f('ix_system_admin_credentials_credential_id'))
            if column_exists('system_admin_credentials', 'public_key'):
                batch_op.drop_column('public_key')
            if column_exists('system_admin_credentials', 'aaguid'):
                batch_op.drop_column('aaguid')
            if column_exists('system_admin_credentials', 'sign_count'):
                batch_op.drop_column('sign_count')
            if column_exists('system_admin_credentials', 'transports'):
                batch_op.drop_column('transports')

    if table_exists('tap_events'):
        with op.batch_alter_table('tap_events', schema=None) as batch_op:
            if not index_exists('tap_events', 'ix_tap_events_is_deleted'):
                batch_op.create_index(batch_op.f('ix_tap_events_is_deleted'), ['is_deleted'], unique=False)

    if table_exists('teacher_blocks'):
        with op.batch_alter_table('teacher_blocks', schema=None) as batch_op:
            if constraint_exists('teacher_blocks', 'teacher_blocks_student_id_fkey', 'foreignkey'):
                batch_op.drop_constraint(batch_op.f('teacher_blocks_student_id_fkey'), type_='foreignkey')
                batch_op.create_foreign_key(None, 'students', ['student_id'], ['id'])

    if table_exists('transaction'):
        with op.batch_alter_table('transaction', schema=None) as batch_op:
            if index_exists('transaction', 'ix_transaction_student_join_code'):
                batch_op.drop_index(batch_op.f('ix_transaction_student_join_code'))
            if index_exists('transaction', 'ix_transaction_teacher_id'):
                batch_op.drop_index(batch_op.f('ix_transaction_teacher_id'))
            if constraint_exists('transaction', 'fk_transaction_teacher_id_admins', 'foreignkey'):
                batch_op.drop_constraint(batch_op.f('fk_transaction_teacher_id_admins'), type_='foreignkey')
                batch_op.create_foreign_key(None, 'admins', ['teacher_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transaction_teacher_id_admins'), 'admins', ['teacher_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_transaction_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transaction_student_join_code'), ['student_id', 'join_code'], unique=False)

    with op.batch_alter_table('teacher_blocks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('teacher_blocks_student_id_fkey'), 'students', ['student_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('tap_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tap_events_is_deleted'))

    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transports', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sign_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aaguid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_system_admin_credentials_credential_id'), ['credential_id'], unique=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_students_teacher_id'), ['teacher_id'], unique=False)
        batch_op.alter_column('has_completed_profile_migration',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('student_recovery_codes', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('student_recovery_codes_recovery_request_id_fkey'), 'recovery_requests', ['recovery_request_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('student_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_items_student_join_code'), ['student_id', 'join_code'], unique=False)

    with op.batch_alter_table('student_insurance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_insurance_student_join_code'), ['student_id', 'join_code'], unique=False)

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('late_fee', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_rent_settings_teacher_id'))
        batch_op.alter_column('prevent_purchase_when_late',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('allow_incremental_payment',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('bill_preview_days',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('7'))
        batch_op.alter_column('bill_preview_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('late_penalty_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'once'::character varying"))
        batch_op.alter_column('late_penalty_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'10'::double precision"))
        batch_op.alter_column('frequency_type',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'monthly'::character varying"))
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_payments_student_join_code'), ['student_id', 'join_code'], unique=False)

    with op.batch_alter_table('rent_items', schema=None) as batch_op:
        batch_op.alter_column('store_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payroll_settings_teacher_id'))
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payroll_rewards', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('payroll_fines', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_insurance_policies_teacher_id'), 'admins', ['teacher_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_insurance_policies_policy_code'))
        batch_op.create_index(batch_op.f('ix_insurance_policies_policy_code'), ['policy_code'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('uq_insurance_policies_policy_code'), ['policy_code'], postgresql_nulls_not_distinct=False)
        batch_op.alter_column('bundle_discount_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.alter_column('enable_repurchase_cooldown',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('is_monetary',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('policy_code',
               existing_type=sa.VARCHAR(length=16),
               nullable=True)

    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hall_pass_settings_teacher_id'))
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hall_pass_logs_student_join_code'), ['student_id', 'join_code'], unique=False)

    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_banking_settings_teacher_id'))
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transports', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('sign_count', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('aaguid', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('public_key', postgresql.BYTEA(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('ix_admin_credentials_credential_id'), ['credential_id'], unique=True)

    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_teacher_window')
        batch_op.drop_index(batch_op.f('ix_analytics_snapshots_join_code'))
        batch_op.drop_index('ix_analytics_join_code_window')
        batch_op.drop_index('ix_analytics_computed_at')

    op.drop_table('analytics_snapshots')
    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_events_type')
        batch_op.drop_index('ix_analytics_events_teacher_date')
        batch_op.drop_index('ix_analytics_events_join_code_date')
        batch_op.drop_index(batch_op.f('ix_analytics_events_join_code'))

    op.drop_table('analytics_events')
    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_analytics_alerts_triggered')
        batch_op.drop_index('ix_analytics_alerts_teacher_active')
        batch_op.drop_index('ix_analytics_alerts_severity')
        batch_op.drop_index('ix_analytics_alerts_join_code_active')
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_join_code'))

    op.drop_table('analytics_alerts')
    # ### end Alembic commands ###
