"""Set cumulative sec columns to not null with default zero

Revision ID: 2118b1d00805
Revises: d0ecd9d002b4
Create Date: 2025-07-09 20:02:28.362185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2118b1d00805'
down_revision = 'd0ecd9d002b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('cumulative_daily_sec',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cumulative_payroll_sec',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('cumulative_payroll_sec',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('cumulative_daily_sec',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
