"""Remove second_factor_secret from Student model

Revision ID: 283d887e9b15
Revises: 7ed94f24520a
Create Date: 2025-07-06 17:05:51.677907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '283d887e9b15'
down_revision = '7ed94f24520a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('second_factor_secret')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_factor_secret', sa.VARCHAR(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
