"""Add missing class_id to analytics and other models

Revision ID: 31bb6bbbe012
Revises: 572702bb6357
Create Date: 2026-04-25 08:41:52.269896

"""
from alembic import op
import sqlalchemy as sa


# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def foreign_key_exists(table_name, fk_name):
    """Check if a foreign key exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        return fk_name in fks
    except Exception:
        return False

def get_foreign_keys_by_column(table_name, column_name):
    """
    Get foreign key constraints that reference a specific column.
    
    Use this instead of hardcoding FK names in downgrade.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        return [
            fk for fk in inspector.get_foreign_keys(table_name)
            if column_name in fk['constrained_columns']
        ]
    except Exception:
        return []

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

# revision identifiers, used by Alembic.
revision = '31bb6bbbe012'
down_revision = '572702bb6357'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analytics_alerts', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_analytics_alerts_class_id'), 'analytics_alerts', ['class_id'], unique=False)
    op.create_foreign_key(None, 'analytics_alerts', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('analytics_events', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_analytics_events_class_id'), 'analytics_events', ['class_id'], unique=False)
    op.create_foreign_key(None, 'analytics_events', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('analytics_snapshots', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_analytics_snapshots_class_id'), 'analytics_snapshots', ['class_id'], unique=False)
    op.create_foreign_key(None, 'analytics_snapshots', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('announcements', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_announcements_class_id'), 'announcements', ['class_id'], unique=False)
    op.create_foreign_key(None, 'announcements', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('insurance_policy_blocks', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_insurance_policy_blocks_class_id'), 'insurance_policy_blocks', ['class_id'], unique=False)
    op.create_foreign_key(None, 'insurance_policy_blocks', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('issue_resolution_actions', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_issue_resolution_actions_class_id'), 'issue_resolution_actions', ['class_id'], unique=False)
    op.create_foreign_key(None, 'issue_resolution_actions', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('issue_status_history', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_issue_status_history_class_id'), 'issue_status_history', ['class_id'], unique=False)
    op.create_foreign_key(None, 'issue_status_history', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('payroll_fines', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_payroll_fines_class_id'), 'payroll_fines', ['class_id'], unique=False)
    op.create_foreign_key(None, 'payroll_fines', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('payroll_rewards', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_payroll_rewards_class_id'), 'payroll_rewards', ['class_id'], unique=False)
    op.create_foreign_key(None, 'payroll_rewards', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('store_item_blocks', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_store_item_blocks_class_id'), 'store_item_blocks', ['class_id'], unique=False)
    op.create_foreign_key(None, 'store_item_blocks', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'store_item_blocks', type_='foreignkey')
    op.drop_index(op.f('ix_store_item_blocks_class_id'), table_name='store_item_blocks')
    op.drop_column('store_item_blocks', 'class_id')
    op.drop_constraint(None, 'payroll_rewards', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_rewards_class_id'), table_name='payroll_rewards')
    op.drop_column('payroll_rewards', 'class_id')
    op.drop_constraint(None, 'payroll_fines', type_='foreignkey')
    op.drop_index(op.f('ix_payroll_fines_class_id'), table_name='payroll_fines')
    op.drop_column('payroll_fines', 'class_id')
    op.drop_constraint(None, 'issue_status_history', type_='foreignkey')
    op.drop_index(op.f('ix_issue_status_history_class_id'), table_name='issue_status_history')
    op.drop_column('issue_status_history', 'class_id')
    op.drop_constraint(None, 'issue_resolution_actions', type_='foreignkey')
    op.drop_index(op.f('ix_issue_resolution_actions_class_id'), table_name='issue_resolution_actions')
    op.drop_column('issue_resolution_actions', 'class_id')
    op.drop_constraint(None, 'insurance_policy_blocks', type_='foreignkey')
    op.drop_index(op.f('ix_insurance_policy_blocks_class_id'), table_name='insurance_policy_blocks')
    op.drop_column('insurance_policy_blocks', 'class_id')
    op.drop_index(op.f('ix_class_economies_created_by_admin_id'), table_name='class_economies')
    op.create_unique_constraint(op.f('uq_class_economies_class_id'), 'class_economies', ['class_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_class_economies_created_by'), 'class_economies', ['created_by_admin_id'], unique=False)
    op.drop_constraint(None, 'announcements', type_='foreignkey')
    op.drop_index(op.f('ix_announcements_class_id'), table_name='announcements')
    op.drop_column('announcements', 'class_id')
    op.drop_constraint(None, 'analytics_snapshots', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_snapshots_class_id'), table_name='analytics_snapshots')
    op.drop_column('analytics_snapshots', 'class_id')
    op.drop_constraint(None, 'analytics_events', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_events_class_id'), table_name='analytics_events')
    op.drop_column('analytics_events', 'class_id')
    op.drop_constraint(None, 'analytics_alerts', type_='foreignkey')
    op.drop_index(op.f('ix_analytics_alerts_class_id'), table_name='analytics_alerts')
    op.drop_column('analytics_alerts', 'class_id')
    # ### end Alembic commands ###
