"""add widget tracking to teacher onboarding

Revision ID: 3d66ea6ec5d3
Revises: 56612765d072
Create Date: 2026-01-01 18:45:44.557416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d66ea6ec5d3'
down_revision = '56612765d072'
branch_labels = None
depends_on = None

# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_onboarding', schema=None) as batch_op:
        if not column_exists('teacher_onboarding', 'widget_tasks_completed'):
            batch_op.add_column(sa.Column('widget_tasks_completed', sa.JSON(), nullable=False, server_default='{}'))
        if not column_exists('teacher_onboarding', 'widget_dismissed'):
            batch_op.add_column(sa.Column('widget_dismissed', sa.Boolean(), nullable=False, server_default='false'))
        if not column_exists('teacher_onboarding', 'widget_dismissed_at'):
            batch_op.add_column(sa.Column('widget_dismissed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('teacher_onboarding', schema=None) as batch_op:
        batch_op.drop_column('widget_dismissed_at')
        batch_op.drop_column('widget_dismissed')
        batch_op.drop_column('widget_tasks_completed')

    # ### end Alembic commands ###
