"""update passkey credential table

Revision ID: 56612765d072
Revises: ed9de5ef6f79
Create Date: 2025-12-31 01:42:46.371146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56612765d072'
down_revision = 'ed9de5ef6f79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed index drops because indexes were never created in the previous migration
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    old_fk_name = None
    existing_fks = list(inspector.get_foreign_keys('system_admin_credentials'))
    # Find the existing FK name for system_admin_id if one exists (SQLite may leave this unnamed)
    for fk in existing_fks:
        if 'system_admin_id' in fk.get('constrained_columns', []):
            old_fk_name = fk.get('name')
            break

    # Clean up any leftover SQLite temp tables from a prior failed batch migration
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_admin_credentials")
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_system_admin_credentials")

    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('credential_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)

    # Make system_admin_credentials changes idempotent
    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        # Refresh inspector info for columns
        cols = {c['name'] for c in inspector.get_columns('system_admin_credentials')}

        # Ensure credential_id is Text and nullable
        batch_op.alter_column('credential_id',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               nullable=True)

        # Add sysadmin_id if missing
        if 'sysadmin_id' not in cols:
            batch_op.add_column(sa.Column('sysadmin_id', sa.Integer(), nullable=False))
        # Drop old FK on system_admin_id if present
        if old_fk_name:
            batch_op.drop_constraint(old_fk_name, type_='foreignkey')
        # Create FK on sysadmin_id if not already present
        has_sysadmin_fk = any(
            'sysadmin_id' in fk.get('constrained_columns', []) and fk.get('referred_table') == 'system_admins'
            for fk in existing_fks
        )
        if not has_sysadmin_fk:
            batch_op.create_foreign_key('fk_system_admin_credentials_sysadmin_id', 'system_admins', ['sysadmin_id'], ['id'], ondelete='CASCADE')
        # Drop legacy column if it exists
        if 'system_admin_id' in cols:
            batch_op.drop_column('system_admin_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Removed index creations because indexes were never in the original schema

    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_admin_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint('fk_system_admin_credentials_sysadmin_id', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('system_admin_credentials_system_admin_id_fkey'), 'system_admins', ['system_admin_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('credential_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('sysadmin_id')

    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('credential_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
