"""Remove cumulative sec columns from Student

Revision ID: 8a4ca17f506f
Revises: d1b3c4d5e6f7
Create Date: 2025-10-07 04:34:07.456940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a4ca17f506f'
down_revision = 'd1b3c4d5e6f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_column('cumulative_daily_sec')
        batch_op.drop_column('cumulative_payroll_sec')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_payroll_sec', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cumulative_daily_sec', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
