"""add hall pass type and queue limit

Revision ID: 8cb5cd7c2e72
Revises: 90f5161ac055
Create Date: 2026-01-09 06:32:44.363824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cb5cd7c2e72'
down_revision = '90f5161ac055'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_types', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.drop_column('pass_types')

    # ### end Alembic commands ###
