"""Add store item models and remove purchase model

Revision ID: 8f4a660d5082
Revises: 5343a19b72e6
Create Date: 2025-09-29 03:35:07.283915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8f4a660d5082'
down_revision = '5343a19b72e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('inventory', sa.Integer(), nullable=True),
    sa.Column('limit_per_student', sa.Integer(), nullable=True),
    sa.Column('auto_delist_date', sa.DateTime(), nullable=True),
    sa.Column('auto_expiry_days', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('store_item_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('redemption_details', sa.Text(), nullable=True),
    sa.Column('redemption_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['store_item_id'], ['store_items.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('purchase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('item_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('redeemed', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('date_purchased', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='purchase_student_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='purchase_pkey')
    )
    op.drop_table('student_items')
    op.drop_table('store_items')
    # ### end Alembic commands ###
