"""Encrypt student first_name

Revision ID: 9e7a8d4f5c6b
Revises: 8f4a660d5082
Create Date: 2025-10-02 21:50:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e7a8d4f5c6b'
down_revision = '8f4a660d5082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.LargeBinary(),
               nullable=False,
               postgresql_using='first_name::bytea')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrading will leave the data in an encrypted state.
    # A manual data migration would be needed to decrypt the names.
    op.alter_column('students', 'first_name',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               postgresql_using='first_name::varchar')
    # ### end Alembic commands ###