"""empty message

Revision ID: d0ecd9d002b4
Revises: 283d887e9b15
Create Date: 2025-07-08 22:46:10.049808

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd0ecd9d002b4'
down_revision = '283d887e9b15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cumulative_daily_sec', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cumulative_payroll_sec', sa.Integer(), nullable=True))
        batch_op.drop_column('last_tap_in')
        batch_op.drop_column('last_tap_out')

    with op.batch_alter_table('tap_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('counted', sa.Boolean(), nullable=True))

    # Backfill data for action:
    op.execute("UPDATE tap_sessions SET action = 'tap_in' WHERE tap_out_time IS NULL;")
    op.execute("UPDATE tap_sessions SET action = 'tap_out' WHERE tap_out_time IS NOT NULL;")

    # Backfill data for status:
    op.execute("UPDATE tap_sessions SET status = 'active' WHERE tap_out_time IS NULL;")
    op.execute("UPDATE tap_sessions SET status = 'inactive' WHERE tap_out_time IS NOT NULL;")

    # Clear tap_in_time for tap_out entries
    op.execute("UPDATE tap_sessions SET tap_in_time = NULL WHERE action = 'tap_out';")
    # Clear tap_out_time for tap_in entries
    op.execute("UPDATE tap_sessions SET tap_out_time = NULL WHERE action = 'tap_in';")

    # Alter columns to enforce NOT NULL:
    with op.batch_alter_table('tap_sessions', schema=None) as batch_op:
        batch_op.alter_column('action', nullable=False)
        batch_op.alter_column('status', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tap_sessions', schema=None) as batch_op:
        batch_op.drop_column('counted')
        batch_op.drop_column('status')
        batch_op.drop_column('action')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_tap_out', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('last_tap_in', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('cumulative_payroll_sec')
        batch_op.drop_column('cumulative_daily_sec')

    # ### end Alembic commands ###
