"""Add hall pass models

Revision ID: f5a1e3e4d7c8
Revises: d0ecd9d002b4
Create Date: 2025-10-02 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a1e3e4d7c8'
down_revision = 'd0ecd9d002b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hall_passes', sa.Integer(), nullable=True))
        batch_op.drop_column('passes_left')

    op.create_table('hall_pass_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('request_time', sa.DateTime(), nullable=False),
    sa.Column('decision_time', sa.DateTime(), nullable=True),
    sa.Column('left_time', sa.DateTime(), nullable=True),
    sa.Column('return_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('passes_left', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('hall_passes')

    op.drop_table('hall_pass_logs')
    # ### end Alembic commands ###