"""Add pass_number and period to hall_pass_logs

Revision ID: h1i2j3k4l5m6
Revises: e5f6g7h8i9j0
Create Date: 2025-11-17 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'h1i2j3k4l5m6'
down_revision = 'e5f6g7h8i9j0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pass_number', sa.String(length=3), nullable=True))
        batch_op.add_column(sa.Column('period', sa.String(length=10), nullable=True))
        batch_op.create_unique_constraint('uq_hall_pass_logs_pass_number', ['pass_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.drop_constraint('uq_hall_pass_logs_pass_number', type_='unique')
        batch_op.drop_column('period')
        batch_op.drop_column('pass_number')
    # ### end Alembic commands ###
