"""Add automatic discount fields to StoreItem, BankingSettings, and Transaction

Revision ID: 04884f00e4af
Revises: h7i8j9k0l1m2
Create Date: 2026-01-07 01:23:50.327687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04884f00e4af'
down_revision = 'h7i8j9k0l1m2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('savings_buffer_multiplier', sa.Float(), nullable=True))

    with op.batch_alter_table('rent_items', schema=None) as batch_op:
        batch_op.alter_column('store_price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(precision=10, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_behavior', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount_tier', sa.String(length=10), nullable=True))

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_applied', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('discount_behavior', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('discount_tier', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('discount_percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('discount_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('discount_reason')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('discount_percentage')
        batch_op.drop_column('discount_tier')
        batch_op.drop_column('discount_behavior')
        batch_op.drop_column('discount_applied')

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.drop_column('discount_tier')
        batch_op.drop_column('discount_behavior')

    with op.batch_alter_table('rent_items', schema=None) as batch_op:
        batch_op.alter_column('store_price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)

    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.drop_column('savings_buffer_multiplier')

    # ### end Alembic commands ###
