"""Drop legacy teacher_id column

Revision ID: 1e07c37d3c7c
Revises: 8cb5cd7c2e72
Create Date: 2026-01-12 02:12:39.979694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e07c37d3c7c'
down_revision = '8cb5cd7c2e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        # Use explicit constraint name for consistency between upgrade and downgrade
        batch_op.drop_constraint('students_teacher_id_fkey', type_='foreignkey')
        batch_op.drop_column('teacher_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        # Use explicit constraint name for consistency between upgrade and downgrade
        batch_op.create_foreign_key('students_teacher_id_fkey', 'admins', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
