"""Drop legacy teacher_id column

Revision ID: 1e07c37d3c7c
Revises: 8cb5cd7c2e72
Create Date: 2026-01-12 02:12:39.979694

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.engine.reflection import Inspector


# revision identifiers, used by Alembic.
revision = '1e07c37d3c7c'
down_revision = '8cb5cd7c2e72'
branch_labels = None
depends_on = None


def upgrade():
    # Dynamically find the Foreign Key constraint for 'teacher_id'
    # This prevents errors if the constraint has a non-standard name or is missing
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    fks = inspector.get_foreign_keys('students')
    fk_name = None
    for fk in fks:
        # Check if this FK constrains the 'teacher_id' column
        if 'teacher_id' in fk['constrained_columns']:
            fk_name = fk['name']
            break
            
    with op.batch_alter_table('students', schema=None) as batch_op:
        if fk_name:
            # If we found it, drop it by its actual name
            batch_op.drop_constraint(fk_name, type_='foreignkey')
        else:
            # If not found, log/ignore (it might be already dropped or never existed)
            print("WARNING: No Foreign Key found for 'students.teacher_id'. Skipping constraint drop.")
            
        # Drop the column itself
        batch_op.drop_column('teacher_id')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True))
        # Note: We recreate it with the standard name or just a new valid name
        batch_op.create_foreign_key('students_teacher_id_fkey', 'admins', ['teacher_id'], ['id'])

    # ### end Alembic commands ###
