"""Add actor_membership_id to HallPassLog

Revision ID: 2095eed48a99
Revises: 62c2e19b2545
Create Date: 2026-01-28 06:39:56.302679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2095eed48a99'
down_revision = '62c2e19b2545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        # Check if index exists before creating
        # batch_op.create_index('ix_class_economies_status', ['status'], unique=False)
        pass

    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_membership_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_hall_pass_logs_actor_membership_id'), ['actor_membership_id'], unique=False)
        batch_op.create_foreign_key(None, 'class_memberships', ['actor_membership_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        batch_op.drop_index('ix_class_economies_status')

    # ### end Alembic commands ###
