"""Add is_teacher_shadow and shadow_for_admin_id to Student; drop demo_students table

Revision ID: 3afaaf07deff
Revises: de4c14f85857
Create Date: 2026-02-26 06:31:43.574139

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def foreign_key_exists(table_name, fk_name):
    """Check if a foreign key exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        return fk_name in fks
    except Exception:
        return False

def get_foreign_keys_by_column(table_name, column_name):
    """
    Get foreign key constraints that reference a specific column.
    
    Use this instead of hardcoding FK names in downgrade.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        return [
            fk for fk in inspector.get_foreign_keys(table_name)
            if column_name in fk['constrained_columns']
        ]
    except Exception:
        return []

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

# revision identifiers, used by Alembic.
revision = '3afaaf07deff'
down_revision = 'de4c14f85857'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if table_exists('demo_students'):
        op.drop_table('demo_students')
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_teacher_shadow', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('shadow_for_admin_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_students_shadow_for_admin_id'), ['shadow_for_admin_id'], unique=True)
        batch_op.create_foreign_key(None, 'admins', ['shadow_for_admin_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_students_shadow_for_admin_id'))
        batch_op.drop_column('shadow_for_admin_id')
        batch_op.drop_column('is_teacher_shadow')

    op.create_table('demo_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('config_checking_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('config_savings_balance', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('config_hall_passes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('config_insurance_plan', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('config_is_rent_enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('config_period', sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('demo_students_admin_id_fkey')),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('demo_students_student_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('demo_students_pkey')),
    sa.UniqueConstraint('session_id', name=op.f('demo_students_session_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
