"""fix analytics alert

Revision ID: 49775b7f5b89
Revises: 1a4ee2388d62
Create Date: 2026-01-07 05:56:04.938352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '49775b7f5b89'
down_revision = '1a4ee2388d62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete existing analytics_alerts as the schema is changing significantly
    # These are temporary alerts that can be regenerated
    bind = op.get_bind()
    bind.execute(sa.text("DELETE FROM analytics_alerts"))
    
    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alert_key', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('window_type', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('window_start', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('window_end', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('valid_until', sa.DateTime(), nullable=True))
        batch_op.alter_column('what_changed',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_teacher_active'))
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_triggered'))
        batch_op.drop_index(batch_op.f('ix_analytics_alerts_join_code_active'))
        batch_op.create_index('ix_analytics_alerts_join_code_active', ['join_code', 'resolved_at'], unique=False)
        batch_op.create_index('ix_analytics_alerts_window', ['window_type', 'window_start', 'window_end'], unique=False)
        batch_op.create_unique_constraint('uq_analytics_alert_identity', ['alert_key', 'join_code', 'window_type', 'window_start', 'window_end'])
        batch_op.drop_constraint(batch_op.f('analytics_alerts_teacher_id_fkey'), type_='foreignkey')
        batch_op.drop_column('triggered_at')
        batch_op.drop_column('metric_name')
        batch_op.drop_column('alert_type')
        batch_op.drop_column('teacher_id')
        batch_op.drop_column('is_active')
        batch_op.drop_column('current_value')
        batch_op.drop_column('threshold_value')

    # Only create the insurance index if it doesn't already exist
    # The index may already exist from migration 1a4ee2388d62
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    insurance_indexes = [idx['name'] for idx in inspector.get_indexes('insurance_policies')]
    
    if 'ix_insurance_policies_policy_code' not in insurance_indexes:
        with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_insurance_policies_policy_code'), ['policy_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only drop the insurance index if it exists
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    insurance_indexes = [idx['name'] for idx in inspector.get_indexes('insurance_policies')]
    
    if 'ix_insurance_policies_policy_code' in insurance_indexes:
        with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_insurance_policies_policy_code'))

    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('threshold_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('current_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('metric_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key(batch_op.f('analytics_alerts_teacher_id_fkey'), 'admins', ['teacher_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_constraint('uq_analytics_alert_identity', type_='unique')
        batch_op.drop_index('ix_analytics_alerts_window')
        batch_op.drop_index('ix_analytics_alerts_join_code_active')
        batch_op.create_index(batch_op.f('ix_analytics_alerts_join_code_active'), ['join_code', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_alerts_triggered'), ['triggered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_alerts_teacher_active'), ['teacher_id', 'is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_analytics_alerts_severity'), ['severity', 'is_active'], unique=False)
        batch_op.alter_column('what_changed',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.drop_column('valid_until')
        batch_op.drop_column('created_at')
        batch_op.drop_column('window_end')
        batch_op.drop_column('window_start')
        batch_op.drop_column('window_type')
        batch_op.drop_column('alert_key')

    # ### end Alembic commands ###
