"""Add DB CHECK constraints to ClassMembership

Revision ID: 548633d7845c
Revises: cbe38081fda9
Create Date: 2026-02-21 06:20:33.753266

"""
from alembic import op
import sqlalchemy as sa


# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def foreign_key_exists(table_name, fk_name):
    """Check if a foreign key exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        return fk_name in fks
    except Exception:
        return False

def get_foreign_keys_by_column(table_name, column_name):
    """
    Get foreign key constraints that reference a specific column.
    
    Use this instead of hardcoding FK names in downgrade.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        return [
            fk for fk in inspector.get_foreign_keys(table_name)
            if column_name in fk['constrained_columns']
        ]
    except Exception:
        return []

def constraint_exists(table_name, constraint_name):
    """Check if a constraint exists on a table."""
    conn = op.get_bind()
    # Check constraints aren't directly available in inspector in older SQLAlchemy
    # We'll use raw SQL for Postgres
    try:
        result = conn.execute(sa.text(
            "SELECT 1 FROM pg_constraint WHERE conname = :name"
        ), {"name": constraint_name})
        return result.fetchone() is not None
    except Exception:
        return False

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

# revision identifiers, used by Alembic.
revision = '548633d7845c'
down_revision = 'cbe38081fda9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        if not constraint_exists('class_memberships', 'ck_membership_xor'):
            batch_op.create_check_constraint(
                'ck_membership_xor',
                "((admin_id IS NOT NULL AND student_id IS NULL) OR (admin_id IS NULL AND student_id IS NOT NULL))"
            )
        if not constraint_exists('class_memberships', 'ck_membership_role_consistency'):
            batch_op.create_check_constraint(
                'ck_membership_role_consistency',
                "((admin_id IS NOT NULL AND role = 'admin') OR (student_id IS NOT NULL AND role = 'student'))"
            )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        if constraint_exists('class_memberships', 'ck_membership_role_consistency'):
            batch_op.drop_constraint('ck_membership_role_consistency', type_='check')
        if constraint_exists('class_memberships', 'ck_membership_xor'):
            batch_op.drop_constraint('ck_membership_xor', type_='check')
    # ### end Alembic commands ###
