"""add nullable false to issue boolean fields

Revision ID: 55f079e43ae6
Revises: 998d84f1db21
Create Date: 2025-12-27 19:13:34.182439

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f079e43ae6'
down_revision = '998d84f1db21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('share_class_name_with_sysadmin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('eligible_for_reward',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('eligible_for_reward',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('share_class_name_with_sysadmin',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###
