"""Re-sync missing v2 columns

Revision ID: 572702bb6357
Revises: 1c39e37f484c
Create Date: 2026-04-25 08:39:04.162987

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uuid

# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def foreign_key_exists(table_name, fk_name):
    """Check if a foreign key exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        return fk_name in fks
    except Exception:
        return False

def get_foreign_keys_by_column(table_name, column_name):
    """
    Get foreign key constraints that reference a specific column.
    
    Use this instead of hardcoding FK names in downgrade.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        return [
            fk for fk in inspector.get_foreign_keys(table_name)
            if column_name in fk['constrained_columns']
        ]
    except Exception:
        return []

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

# revision identifiers, used by Alembic.
revision = '572702bb6357'
down_revision = '1c39e37f484c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure enum exists
    op.execute("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'classmembershiprole') THEN CREATE TYPE classmembershiprole AS ENUM ('admin', 'student'); END IF; END $$")

    op.create_index('ix_analytics_alerts_join_code_active', 'analytics_alerts', ['join_code', 'resolved_at'], unique=False)
    op.alter_column('banking_settings', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('class_economies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('class_economies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('class_memberships', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    # Use manual SQL for type change with USING clause
    op.execute("ALTER TABLE class_memberships ALTER COLUMN role TYPE classmembershiprole USING role::classmembershiprole")
    op.alter_column('class_memberships', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('class_memberships', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index(op.f('ix_class_memberships_join_code_role'), table_name='class_memberships')
    op.drop_constraint(op.f('uq_class_membership_admin'), 'class_memberships', type_='unique')
    op.create_unique_constraint('uq_class_membership_admin', 'class_memberships', ['class_id', 'admin_id'])
    op.drop_constraint(op.f('uq_class_membership_student'), 'class_memberships', type_='unique')
    op.create_unique_constraint('uq_class_membership_student', 'class_memberships', ['class_id', 'student_id'])
    op.drop_constraint(op.f('uq_feature_settings_class_id'), 'feature_settings', type_='unique')
    op.drop_index(op.f('ix_feature_settings_class_id'), table_name='feature_settings')
    op.create_index(op.f('ix_feature_settings_class_id'), 'feature_settings', ['class_id'], unique=True)
    op.add_column('hall_pass_logs', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_hall_pass_logs_class_id'), 'hall_pass_logs', ['class_id'], unique=False)
    op.create_foreign_key(None, 'hall_pass_logs', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_hall_pass_settings_class_id'), 'hall_pass_settings', type_='unique')
    op.drop_index(op.f('ix_hall_pass_settings_class_id'), table_name='hall_pass_settings')
    op.create_index(op.f('ix_hall_pass_settings_class_id'), 'hall_pass_settings', ['class_id'], unique=True)
    op.add_column('insurance_claims', sa.Column('seat_id', sa.Integer(), nullable=True))
    op.add_column('insurance_claims', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.alter_column('insurance_claims', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_insurance_claims_class_id'), 'insurance_claims', ['class_id'], unique=False)
    op.create_index(op.f('ix_insurance_claims_seat_id'), 'insurance_claims', ['seat_id'], unique=False)
    op.create_foreign_key(None, 'insurance_claims', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'insurance_claims', 'seats', ['seat_id'], ['id'], ondelete='SET NULL')
    op.alter_column('insurance_policies', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('issues', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.add_column('issues', sa.Column('seat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_issues_class_id'), 'issues', ['class_id'], unique=False)
    op.create_index(op.f('ix_issues_seat_id'), 'issues', ['seat_id'], unique=False)
    op.create_foreign_key(None, 'issues', 'seats', ['seat_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'issues', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('uq_payroll_cache_class_id'), 'payroll_cache', type_='unique')
    op.drop_index(op.f('ix_payroll_cache_class_id'), table_name='payroll_cache')
    op.create_index(op.f('ix_payroll_cache_class_id'), 'payroll_cache', ['class_id'], unique=True)
    op.alter_column('payroll_settings', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('redemption_audit_logs', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.add_column('redemption_audit_logs', sa.Column('seat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_redemption_audit_logs_class_id'), 'redemption_audit_logs', ['class_id'], unique=False)
    op.create_index(op.f('ix_redemption_audit_logs_seat_id'), 'redemption_audit_logs', ['seat_id'], unique=False)
    op.create_foreign_key(None, 'redemption_audit_logs', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'redemption_audit_logs', 'seats', ['seat_id'], ['id'], ondelete='SET NULL')
    op.alter_column('rent_items', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('rent_settings', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.alter_column('seats', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('seats_public_id_key'), 'seats', type_='unique')
    op.alter_column('store_items', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('student_blocks', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_student_blocks_class_id'), 'student_blocks', ['class_id'], unique=False)
    op.create_foreign_key(None, 'student_blocks', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('student_items', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.add_column('student_items', sa.Column('seat_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_student_items_class_id'), 'student_items', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_items_seat_id'), 'student_items', ['seat_id'], unique=False)
    op.create_foreign_key(None, 'student_items', 'seats', ['seat_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'student_items', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.add_column('student_teachers', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_student_teachers_class_id'), 'student_teachers', ['class_id'], unique=False)
    op.create_foreign_key(None, 'student_teachers', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.alter_column('students', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.add_column('tap_events', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index('ix_tap_event_student_period_timestamp', 'tap_events', ['student_id', 'period', 'timestamp'], unique=False)
    op.create_index(op.f('ix_tap_events_class_id'), 'tap_events', ['class_id'], unique=False)
    op.create_foreign_key(None, 'tap_events', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.alter_column('teacher_blocks', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_admins_public_id'), table_name='teachers')
    op.create_index(op.f('ix_teachers_public_id'), 'teachers', ['public_id'], unique=True)
    op.drop_index(op.f('ix_ticket_correlation_pack_class_id'), table_name='ticket_correlation_pack')
    op.add_column('user_reports', sa.Column('class_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_user_reports_class_id'), 'user_reports', ['class_id'], unique=False)
    op.create_foreign_key(None, 'user_reports', 'class_economies', ['class_id'], ['class_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('users_public_id_key'), 'users', type_='unique')
    op.drop_constraint(op.f('users_username_key'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('users_username_key'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('users_public_id_key'), 'users', ['public_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_reports', type_='foreignkey')
    op.drop_index(op.f('ix_user_reports_class_id'), table_name='user_reports')
    op.drop_column('user_reports', 'class_id')
    op.create_index(op.f('ix_ticket_correlation_pack_class_id'), 'ticket_correlation_pack', ['class_id'], unique=False)
    op.drop_index(op.f('ix_teachers_public_id'), table_name='teachers')
    op.create_index(op.f('ix_admins_public_id'), 'teachers', ['public_id'], unique=True)
    op.alter_column('teacher_blocks', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'tap_events', type_='foreignkey')
    op.drop_index(op.f('ix_tap_events_class_id'), table_name='tap_events')
    op.drop_index('ix_tap_event_student_period_timestamp', table_name='tap_events')
    op.drop_column('tap_events', 'class_id')
    op.alter_column('students', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'student_teachers', type_='foreignkey')
    op.drop_index(op.f('ix_student_teachers_class_id'), table_name='student_teachers')
    op.drop_column('student_teachers', 'class_id')
    op.drop_constraint(None, 'student_items', type_='foreignkey')
    op.drop_constraint(None, 'student_items', type_='foreignkey')
    op.drop_index(op.f('ix_student_items_seat_id'), table_name='student_items')
    op.drop_index(op.f('ix_student_items_class_id'), table_name='student_items')
    op.drop_column('student_items', 'seat_id')
    op.drop_column('student_items', 'class_id')
    op.drop_constraint(None, 'student_blocks', type_='foreignkey')
    op.drop_index(op.f('ix_student_blocks_class_id'), table_name='student_blocks')
    op.drop_column('student_blocks', 'class_id')
    op.alter_column('store_items', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.create_unique_constraint(op.f('seats_public_id_key'), 'seats', ['public_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('seats', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rent_settings', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.alter_column('rent_items', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'redemption_audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'redemption_audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_redemption_audit_logs_seat_id'), table_name='redemption_audit_logs')
    op.drop_index(op.f('ix_redemption_audit_logs_class_id'), table_name='redemption_audit_logs')
    op.drop_column('redemption_audit_logs', 'seat_id')
    op.drop_column('redemption_audit_logs', 'class_id')
    op.alter_column('payroll_settings', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index(op.f('ix_payroll_cache_class_id'), table_name='payroll_cache')
    op.create_index(op.f('ix_payroll_cache_class_id'), 'payroll_cache', ['class_id'], unique=False)
    op.create_unique_constraint(op.f('uq_payroll_cache_class_id'), 'payroll_cache', ['class_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_constraint(None, 'issues', type_='foreignkey')
    op.drop_index(op.f('ix_issues_seat_id'), table_name='issues')
    op.drop_index(op.f('ix_issues_class_id'), table_name='issues')
    op.drop_column('issues', 'seat_id')
    op.drop_column('issues', 'class_id')
    op.alter_column('insurance_policies', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.drop_constraint(None, 'insurance_claims', type_='foreignkey')
    op.drop_index(op.f('ix_insurance_claims_seat_id'), table_name='insurance_claims')
    op.drop_index(op.f('ix_insurance_claims_class_id'), table_name='insurance_claims')
    op.alter_column('insurance_claims', 'student_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('insurance_claims', 'class_id')
    op.drop_column('insurance_claims', 'seat_id')
    op.drop_index(op.f('ix_hall_pass_settings_class_id'), table_name='hall_pass_settings')
    op.create_index(op.f('ix_hall_pass_settings_class_id'), 'hall_pass_settings', ['class_id'], unique=False)
    op.create_unique_constraint(op.f('uq_hall_pass_settings_class_id'), 'hall_pass_settings', ['class_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'hall_pass_logs', type_='foreignkey')
    op.drop_index(op.f('ix_hall_pass_logs_class_id'), table_name='hall_pass_logs')
    op.drop_column('hall_pass_logs', 'class_id')
    op.drop_index(op.f('ix_feature_settings_class_id'), table_name='feature_settings')
    op.create_index(op.f('ix_feature_settings_class_id'), 'feature_settings', ['class_id'], unique=False)
    op.create_unique_constraint(op.f('uq_feature_settings_class_id'), 'feature_settings', ['class_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_class_membership_student', 'class_memberships', type_='unique')
    op.create_unique_constraint(op.f('uq_class_membership_student'), 'class_memberships', ['join_code', 'student_id'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_class_membership_admin', 'class_memberships', type_='unique')
    op.create_unique_constraint(op.f('uq_class_membership_admin'), 'class_memberships', ['join_code', 'admin_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_class_memberships_join_code_role'), 'class_memberships', ['join_code', 'role'], unique=False)
    op.alter_column('class_memberships', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('class_memberships', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('class_memberships', 'role',
               existing_type=sa.Enum('admin', 'student', name='classmembershiprole'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('class_memberships', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_class_economies_created_by_admin_id'), table_name='class_economies')
    op.create_unique_constraint(op.f('uq_class_economies_class_id'), 'class_economies', ['class_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_class_economies_created_by'), 'class_economies', ['created_by_admin_id'], unique=False)
    op.alter_column('class_economies', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('class_economies', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('banking_settings', 'class_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=False)
    op.drop_index('ix_analytics_alerts_join_code_active', table_name='analytics_alerts')
    # ### end Alembic commands ###
