"""Add join_code to store_items and other missing schema changes

Revision ID: 62c2e19b2545
Revises: d8596b480fa1
Create Date: 2026-01-28 06:32:42.600436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62c2e19b2545'
down_revision = 'd8596b480fa1'
branch_labels = None
depends_on = None



def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def foreign_key_exists(table_name, fk_name):
    """Check if a foreign key exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        return fk_name in fks
    except Exception:
        return False

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('class_join_code_aliases'):
        op.create_table('class_join_code_aliases',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('old_code', sa.String(length=20), nullable=False),
        sa.Column('current_join_code', sa.String(length=20), nullable=False),
        sa.Column('rotated_at', sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(['current_join_code'], ['class_economies.join_code'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('class_join_code_aliases', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_class_join_code_aliases_old_code'), ['old_code'], unique=True)

    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        if not foreign_key_exists('banking_settings', 'banking_settings_join_code_fkey'): # Guessing name or skip if already keyed
             try:
                batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
             except Exception:
                pass

    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        if not column_exists('class_economies', 'created_by_admin_id'):
            batch_op.add_column(sa.Column('created_by_admin_id', sa.Integer(), nullable=True))
            batch_op.create_index('ix_class_economies_created_by', ['created_by_admin_id'], unique=False)
            batch_op.create_foreign_key(None, 'admins', ['created_by_admin_id'], ['id'], ondelete='SET NULL')
        
        if not column_exists('class_economies', 'archived_at'):
             batch_op.add_column(sa.Column('archived_at', sa.DateTime(), nullable=True))
             # batch_op.create_index('ix_class_economies_status', ['status'], unique=False) # Status exists? Assumed.

    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        if column_exists('class_memberships', 'status'):
            if not index_exists('class_memberships', 'ix_class_memberships_admin_status'):
                batch_op.create_index('ix_class_memberships_admin_status', ['admin_id', 'status'], unique=False)
            if not index_exists('class_memberships', 'ix_class_memberships_student_status'):
                batch_op.create_index('ix_class_memberships_student_status', ['student_id', 'status'], unique=False)
        
        if not index_exists('class_memberships', 'ix_class_memberships_join_code_role'):
            batch_op.create_index('ix_class_memberships_join_code_role', ['join_code', 'role'], unique=False)

    with op.batch_alter_table('feature_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('payroll_fines', schema=None) as batch_op:
        if not column_exists('payroll_fines', 'join_code'):
            batch_op.add_column(sa.Column('join_code', sa.String(length=20), nullable=True))
            batch_op.create_index(batch_op.f('ix_payroll_fines_join_code'), ['join_code'], unique=False)
            batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('payroll_rewards', schema=None) as batch_op:
        if not column_exists('payroll_rewards', 'join_code'):
            batch_op.add_column(sa.Column('join_code', sa.String(length=20), nullable=True))
            batch_op.create_index(batch_op.f('ix_payroll_rewards_join_code'), ['join_code'], unique=False)
            batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        if not column_exists('store_items', 'join_code'):
            batch_op.add_column(sa.Column('join_code', sa.String(length=20), nullable=True))
            batch_op.create_index(batch_op.f('ix_store_items_join_code'), ['join_code'], unique=False)
            batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transaction_actor_membership_id'), ['actor_membership_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('transaction_actor_membership_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'class_memberships', ['actor_membership_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('transaction_actor_membership_id_fkey'), 'class_memberships', ['actor_membership_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_transaction_actor_membership_id'))

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_store_items_join_code'))
        batch_op.drop_column('join_code')

    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('payroll_rewards', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payroll_rewards_join_code'))
        batch_op.drop_column('join_code')

    with op.batch_alter_table('payroll_fines', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_payroll_fines_join_code'))
        batch_op.drop_column('join_code')

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('feature_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        batch_op.drop_index('ix_class_memberships_student_status')
        batch_op.drop_index('ix_class_memberships_join_code_role')
        batch_op.drop_index('ix_class_memberships_admin_status')

    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index('ix_class_economies_status')
        batch_op.drop_index('ix_class_economies_created_by')
        batch_op.drop_column('archived_at')
        batch_op.drop_column('created_by_admin_id')

    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('class_join_code_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_class_join_code_aliases_old_code'))

    op.drop_table('class_join_code_aliases')
    # ### end Alembic commands ###
