"""Add admin_credential table for teacher passkey authentication

Revision ID: 64f0fdfc2079
Revises: d8a6a0ae85bc
Create Date: 2025-12-25 13:02:18.995465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '64f0fdfc2079'
down_revision = 'd8a6a0ae85bc'
branch_labels = None
depends_on = None

# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('admin_credentials'):
        op.create_table('admin_credentials',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('admin_id', sa.Integer(), nullable=False),
        sa.Column('credential_id', sa.LargeBinary(), nullable=False),
        sa.Column('public_key', sa.LargeBinary(), nullable=True),
        sa.Column('sign_count', sa.Integer(), nullable=False),
        sa.Column('transports', sa.String(length=255), nullable=True),
        sa.Column('authenticator_name', sa.String(length=100), nullable=True),
        sa.Column('aaguid', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_used', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        if not index_exists('admin_credentials', 'ix_admin_credentials_credential_id'):
            batch_op.create_index(batch_op.f('ix_admin_credentials_credential_id'), ['credential_id'], unique=True)

    if table_exists('admins'):
        with op.batch_alter_table('admins', schema=None) as batch_op:
            if column_exists('admins', 'totp_secret'):
                batch_op.alter_column('totp_secret',
                       existing_type=sa.VARCHAR(length=32),
                       type_=sa.String(length=200),
                       existing_nullable=False)

    if table_exists('system_admin_credentials'):
        with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
            if column_exists('system_admin_credentials', 'public_key'):
                batch_op.alter_column('public_key',
                       existing_type=postgresql.BYTEA(),
                       nullable=True)

    if table_exists('system_admins'):
        with op.batch_alter_table('system_admins', schema=None) as batch_op:
            if column_exists('system_admins', 'totp_secret'):
                batch_op.alter_column('totp_secret',
                       existing_type=sa.VARCHAR(length=32),
                       type_=sa.String(length=200),
                       existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_admins', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('public_key',
               existing_type=postgresql.BYTEA(),
               nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_credentials_credential_id'))

    op.drop_table('admin_credentials')
    # ### end Alembic commands ###
