"""add rent item table

Revision ID: 6feaa660d6c3
Revises: 3d66ea6ec5d3
Create Date: 2026-01-02 06:15:33.909449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6feaa660d6c3'
down_revision = '3d66ea6ec5d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rent_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rent_setting_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_available_in_store', sa.Boolean(), nullable=True),
    sa.Column('store_price', sa.Float(), nullable=True),
    sa.Column('store_item_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rent_setting_id'], ['rent_settings.id'], ),
    sa.ForeignKeyConstraint(['store_item_id'], ['store_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rent_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rent_items_rent_setting_id'), ['rent_setting_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rent_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rent_items_rent_setting_id'))

    op.drop_table('rent_items')
    # ### end Alembic commands ###
