"""Add tos_accepted to Admin

Revision ID: 7ee026ad3ad8
Revises: 9e7a8d4f5c6b
Create Date: 2026-01-09 01:07:13.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ee026ad3ad8'
down_revision = '9e7a8d4f5c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tos_accepted', sa.Boolean(), server_default='false', nullable=False))
        batch_op.add_column(sa.Column('tos_accepted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_column('tos_accepted_at')
        batch_op.drop_column('tos_accepted')

    # ### end Alembic commands ###
