"""Implement table for teacher issue, tracking and reference lookup

Revision ID: 998d84f1db21
Revises: f1g2h3i4j5k6
Create Date: 2025-12-27 18:29:48.954174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '998d84f1db21'
down_revision = 'f1g2h3i4j5k6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('issue_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('student_first_name', sa.String(length=100), nullable=False),
    sa.Column('student_last_initial', sa.String(length=1), nullable=False),
    sa.Column('opaque_student_reference', sa.String(length=64), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=False),
    sa.Column('class_label', sa.String(length=50), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=50), nullable=False),
    sa.Column('student_explanation', sa.Text(), nullable=False),
    sa.Column('student_expected_outcome', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('related_transaction_id', sa.Integer(), nullable=True),
    sa.Column('related_record_type', sa.String(length=50), nullable=True),
    sa.Column('related_record_id', sa.Integer(), nullable=True),
    sa.Column('context_snapshot', sa.JSON(), nullable=True),
    sa.Column('page_url', sa.String(length=500), nullable=True),
    sa.Column('system_metadata', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('teacher_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('teacher_notes', sa.Text(), nullable=True),
    sa.Column('teacher_resolution', sa.String(length=100), nullable=True),
    sa.Column('teacher_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('escalated_at', sa.DateTime(), nullable=True),
    sa.Column('escalation_reason', sa.String(length=200), nullable=True),
    sa.Column('teacher_diagnostic_note', sa.Text(), nullable=True),
    sa.Column('share_class_name_with_sysadmin', sa.Boolean(), nullable=True),
    sa.Column('eligible_for_reward', sa.Boolean(), nullable=True),
    sa.Column('sysadmin_id', sa.Integer(), nullable=True),
    sa.Column('sysadmin_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('sysadmin_notes', sa.Text(), nullable=True),
    sa.Column('sysadmin_resolved_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('closed_by_type', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['issue_categories.id'], ),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['sysadmin_id'], ['system_admins.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issues_join_code'), ['join_code'], unique=False)
        batch_op.create_index('ix_issues_join_code_status', ['join_code', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_opaque_student_reference'), ['opaque_student_reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_student_id'), ['student_id'], unique=False)
        batch_op.create_index('ix_issues_student_status', ['student_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_issues_teacher_id'), ['teacher_id'], unique=False)
        batch_op.create_index('ix_issues_teacher_status', ['teacher_id', 'status'], unique=False)

    op.create_table('issue_resolution_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('action_description', sa.Text(), nullable=True),
    sa.Column('performed_by_type', sa.String(length=20), nullable=False),
    sa.Column('performed_by_id', sa.Integer(), nullable=False),
    sa.Column('related_transaction_id', sa.Integer(), nullable=True),
    sa.Column('amount_changed', sa.Float(), nullable=True),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_resolution_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_resolution_actions_issue_id'), ['issue_id'], unique=False)

    op.create_table('issue_status_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_id', sa.Integer(), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.Column('changed_by_type', sa.String(length=20), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issue_id'], ['issues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issue_status_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issue_status_history_issue_id'), ['issue_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('issue_status_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_status_history_issue_id'))

    op.drop_table('issue_status_history')
    with op.batch_alter_table('issue_resolution_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issue_resolution_actions_issue_id'))

    op.drop_table('issue_resolution_actions')
    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.drop_index('ix_issues_teacher_status')
        batch_op.drop_index(batch_op.f('ix_issues_teacher_id'))
        batch_op.drop_index(batch_op.f('ix_issues_submitted_at'))
        batch_op.drop_index('ix_issues_student_status')
        batch_op.drop_index(batch_op.f('ix_issues_student_id'))
        batch_op.drop_index(batch_op.f('ix_issues_status'))
        batch_op.drop_index(batch_op.f('ix_issues_opaque_student_reference'))
        batch_op.drop_index('ix_issues_join_code_status')
        batch_op.drop_index(batch_op.f('ix_issues_join_code'))

    op.drop_table('issues')
    op.drop_table('issue_categories')
    # ### end Alembic commands ###
