"""Add original_transaction_id to Transaction

Revision ID: a6d4a8239282
Revises: 2765a36d76ff
Create Date: 2026-02-10 06:15:39.526182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6d4a8239282'
down_revision = '2765a36d76ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('original_transaction_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_original_transaction_id', 'transaction', ['original_transaction_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_original_transaction_id', type_='foreignkey')
        batch_op.drop_column('original_transaction_id')

    # ### end Alembic commands ###
