"""add actor_membership_id to transaction

Revision ID: d8596b480fa1
Revises: a8184d13b0a0
Create Date: 2026-01-17 04:59:48.648644

"""
from alembic import op
import sqlalchemy as sa
import app.utils.encryption


# revision identifiers, used by Alembic.
revision = 'd8596b480fa1'
down_revision = 'a8184d13b0a0'
branch_labels = None
depends_on = None



def column_exists(table, column):
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    columns = [c['name'] for c in inspector.get_columns(table)]
    return column in columns

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admins', schema=None) as batch_op:
        if not column_exists('admins', 'display_name'):
            batch_op.add_column(sa.Column('display_name', sa.String(length=100), nullable=True))
        if not column_exists('admins', 'dob_sum_hash'):
            batch_op.add_column(sa.Column('dob_sum_hash', sa.String(length=64), nullable=True))
        if not column_exists('admins', 'salt'):
            batch_op.add_column(sa.Column('salt', sa.LargeBinary(length=16), nullable=True))
        if not column_exists('admins', 'created_at'):
            batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        if not column_exists('admins', 'last_login'):
            batch_op.add_column(sa.Column('last_login', sa.DateTime(), nullable=True))
        if not column_exists('admins', 'has_assigned_students'):
            batch_op.add_column(sa.Column('has_assigned_students', sa.Boolean(), nullable=False, server_default='0')) # Added default to handle NotNull
        if not column_exists('admins', 'tos_accepted'):
            batch_op.add_column(sa.Column('tos_accepted', sa.Boolean(), server_default='false', nullable=False))
        if not column_exists('admins', 'tos_accepted_at'):
            batch_op.add_column(sa.Column('tos_accepted_at', sa.DateTime(), nullable=True))
        
        # Only alter if necessary? Assuming alter is fine.
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        if not column_exists('store_items', 'teacher_id'):
            batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=False))
            batch_op.create_foreign_key(None, 'admins', ['teacher_id'], ['id'])
        if not column_exists('store_items', 'tier'):
            batch_op.add_column(sa.Column('tier', sa.String(length=20), nullable=True))
        if not column_exists('store_items', 'is_long_term_goal'):
            batch_op.add_column(sa.Column('is_long_term_goal', sa.Boolean(), nullable=False, server_default='0'))
        if not column_exists('store_items', 'is_bundle'):
            batch_op.add_column(sa.Column('is_bundle', sa.Boolean(), nullable=False, server_default='0'))
        if not column_exists('store_items', 'bundle_quantity'):
            batch_op.add_column(sa.Column('bundle_quantity', sa.Integer(), nullable=True))
        if not column_exists('store_items', 'bulk_discount_enabled'):
            batch_op.add_column(sa.Column('bulk_discount_enabled', sa.Boolean(), nullable=False, server_default='0'))
        if not column_exists('store_items', 'bulk_discount_quantity'):
            batch_op.add_column(sa.Column('bulk_discount_quantity', sa.Integer(), nullable=True))
        if not column_exists('store_items', 'bulk_discount_percentage'):
            batch_op.add_column(sa.Column('bulk_discount_percentage', sa.Float(), nullable=True))
        if not column_exists('store_items', 'collective_goal_type'):
            batch_op.add_column(sa.Column('collective_goal_type', sa.String(length=20), nullable=True))
        if not column_exists('store_items', 'collective_goal_target'):
            batch_op.add_column(sa.Column('collective_goal_target', sa.Integer(), nullable=True))
        if not column_exists('store_items', 'redemption_prompt'):
            batch_op.add_column(sa.Column('redemption_prompt', sa.Text(), nullable=True))
        
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    with op.batch_alter_table('student_items', schema=None) as batch_op:
        if not column_exists('student_items', 'join_code'):
            batch_op.add_column(sa.Column('join_code', sa.String(length=20), nullable=True))
            batch_op.create_index(batch_op.f('ix_student_items_join_code'), ['join_code'], unique=False)
            batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        if not column_exists('student_items', 'is_from_bundle'):
            batch_op.add_column(sa.Column('is_from_bundle', sa.Boolean(), nullable=False, server_default='0'))
        if not column_exists('student_items', 'bundle_remaining'):
            batch_op.add_column(sa.Column('bundle_remaining', sa.Integer(), nullable=True))
        if not column_exists('student_items', 'quantity_purchased'):
            batch_op.add_column(sa.Column('quantity_purchased', sa.Integer(), nullable=False, server_default='1'))

    with op.batch_alter_table('students', schema=None) as batch_op:
        if not column_exists('students', 'username_lookup_hash'):
            batch_op.add_column(sa.Column('username_lookup_hash', sa.String(length=64), nullable=True))
            batch_op.create_unique_constraint(None, ['username_lookup_hash'])
        if not column_exists('students', 'last_name_hash_by_part'):
            batch_op.add_column(sa.Column('last_name_hash_by_part', sa.JSON(), nullable=True))
        if not column_exists('students', 'hall_passes'):
            batch_op.add_column(sa.Column('hall_passes', sa.Integer(), nullable=True))
        if not column_exists('students', 'has_completed_profile_migration'):
            batch_op.add_column(sa.Column('has_completed_profile_migration', sa.Boolean(), nullable=True))
        
        # Safe to try alter?
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=50),
               type_=app.utils.encryption.PIIEncryptedType(key_env_var='ENCRYPTION_KEY'),
               existing_nullable=False)
        
        if column_exists('students', 'cumulative_daily_sec'):
            batch_op.drop_column('cumulative_daily_sec')
        if column_exists('students', 'cumulative_payroll_sec'):
            batch_op.drop_column('cumulative_payroll_sec')
        if column_exists('students', 'owns_seat'):
            batch_op.drop_column('owns_seat')
        if column_exists('students', 'passes_left'):
            batch_op.drop_column('passes_left')
        if column_exists('students', 'is_property_tax_enabled'):
            batch_op.drop_column('is_property_tax_enabled')

    with op.batch_alter_table('system_admins', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=200),
               existing_nullable=False)

    with op.batch_alter_table('tap_events', schema=None) as batch_op:
        if not column_exists('tap_events', 'join_code'):
             batch_op.add_column(sa.Column('join_code', sa.String(length=20), nullable=True))
             batch_op.create_index(batch_op.f('ix_tap_events_join_code'), ['join_code'], unique=False)
             batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        if not column_exists('tap_events', 'is_deleted'):
             batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0'))
             batch_op.create_index(batch_op.f('ix_tap_events_is_deleted'), ['is_deleted'], unique=False)
        if not column_exists('tap_events', 'deleted_at'):
             batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        if not column_exists('tap_events', 'deleted_by'):
             batch_op.add_column(sa.Column('deleted_by', sa.Integer(), nullable=True))
             batch_op.create_foreign_key(None, 'admins', ['deleted_by'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        if not column_exists('transaction', 'teacher_id'):
            batch_op.add_column(sa.Column('teacher_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'admins', ['teacher_id'], ['id'])
        if not column_exists('transaction', 'actor_membership_id'):
            batch_op.add_column(sa.Column('actor_membership_id', sa.Integer(), nullable=True))
            batch_op.create_foreign_key(None, 'class_memberships', ['actor_membership_id'], ['id'])
        if not column_exists('transaction', 'join_code'):
            batch_op.add_column(sa.Column('join_code', sa.String(length=20), nullable=True))
            batch_op.create_index(batch_op.f('ix_transaction_join_code'), ['join_code'], unique=False)
            batch_op.create_foreign_key(None, 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
            
        batch_op.alter_column('amount',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_transaction_join_code'))
        batch_op.alter_column('amount',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('join_code')
        batch_op.drop_column('actor_membership_id')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('tap_events', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_tap_events_join_code'))
        batch_op.drop_index(batch_op.f('ix_tap_events_is_deleted'))
        batch_op.drop_column('deleted_by')
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')
        batch_op.drop_column('join_code')

    with op.batch_alter_table('system_admins', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_property_tax_enabled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('passes_left', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('owns_seat', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('cumulative_payroll_sec', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('cumulative_daily_sec', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('first_name',
               existing_type=app.utils.encryption.PIIEncryptedType(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
        batch_op.drop_column('has_completed_profile_migration')
        batch_op.drop_column('hall_passes')
        batch_op.drop_column('last_name_hash_by_part')
        batch_op.drop_column('username_lookup_hash')

    with op.batch_alter_table('student_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_student_items_join_code'))
        batch_op.drop_column('quantity_purchased')
        batch_op.drop_column('bundle_remaining')
        batch_op.drop_column('is_from_bundle')
        batch_op.drop_column('join_code')

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=sa.FLOAT(),
               existing_nullable=False)
        batch_op.drop_column('redemption_prompt')
        batch_op.drop_column('collective_goal_target')
        batch_op.drop_column('collective_goal_type')
        batch_op.drop_column('bulk_discount_percentage')
        batch_op.drop_column('bulk_discount_quantity')
        batch_op.drop_column('bulk_discount_enabled')
        batch_op.drop_column('bundle_quantity')
        batch_op.drop_column('is_bundle')
        batch_op.drop_column('is_long_term_goal')
        batch_op.drop_column('tier')
        batch_op.drop_column('teacher_id')

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('totp_secret',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('tos_accepted_at')
        batch_op.drop_column('tos_accepted')
        batch_op.drop_column('has_assigned_students')
        batch_op.drop_column('last_login')
        batch_op.drop_column('created_at')
        batch_op.drop_column('salt')
        batch_op.drop_column('dob_sum_hash')
        batch_op.drop_column('display_name')

    # ### end Alembic commands ###
