"""add_system_admin_credentials_table_for_passkey_auth

Revision ID: d8a6a0ae85bc
Revises: 967a83b70750
Create Date: 2025-12-25 00:14:38.546615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8a6a0ae85bc'
down_revision = '967a83b70750'
branch_labels = None
depends_on = None

# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if not table_exists('system_admin_credentials'):
        op.create_table('system_admin_credentials',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sysadmin_id', sa.Integer(), nullable=False),
        sa.Column('credential_id', sa.LargeBinary(), nullable=False),
        sa.Column('public_key', sa.LargeBinary(), nullable=False),
        sa.Column('sign_count', sa.Integer(), nullable=False),
        sa.Column('transports', sa.String(length=255), nullable=True),
        sa.Column('authenticator_name', sa.String(length=100), nullable=True),
        sa.Column('aaguid', sa.String(length=36), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('last_used', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['sysadmin_id'], ['system_admins.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
    
    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        if not index_exists('system_admin_credentials', 'ix_system_admin_credentials_credential_id'):
            batch_op.create_index(batch_op.f('ix_system_admin_credentials_credential_id'), ['credential_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_system_admin_credentials_credential_id'))

    op.drop_table('system_admin_credentials')
    # ### end Alembic commands ###
