"""Add DB CHECK constraints to ClassMembership

Revision ID: de4c14f85857
Revises: 548633d7845c
Create Date: 2026-02-26 04:24:18.082993

"""
from alembic import op
import sqlalchemy as sa


# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def foreign_key_exists(table_name, fk_name):
    """Check if a foreign key exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        return fk_name in fks
    except Exception:
        return False

def get_foreign_keys_by_column(table_name, column_name):
    """
    Get foreign key constraints that reference a specific column.
    
    Use this instead of hardcoding FK names in downgrade.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        return [
            fk for fk in inspector.get_foreign_keys(table_name)
            if column_name in fk['constrained_columns']
        ]
    except Exception:
        return []

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

# revision identifiers, used by Alembic.
revision = 'de4c14f85857'
down_revision = '548633d7845c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    if index_exists('balance_cache', 'ix_balance_cache_scope'):
        with op.batch_alter_table('balance_cache', schema=None) as batch_op:
            batch_op.drop_index(batch_op.f('ix_balance_cache_scope'))

    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        if column_exists('class_economies', 'status') and not index_exists('class_economies', 'ix_class_economies_status'):
            batch_op.create_index('ix_class_economies_status', ['status'], unique=False)

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admins', ['teacher_id'], ['id'])

    # Backfill missing teacher_id in rent_settings before altering column
    op.execute("""
        UPDATE rent_settings
        SET teacher_id = class_memberships.admin_id
        FROM class_memberships
        WHERE rent_settings.join_code = class_memberships.join_code
          AND class_memberships.role = 'admin'
          AND class_memberships.admin_id IS NOT NULL
          AND rent_settings.teacher_id IS NULL
    """)
    # Delete any dangling rent_settings without a valid teacher_id/join_code to satisfy NOT NULL
    op.execute("""
        DELETE FROM rent_settings
        WHERE teacher_id IS NULL
    """)

    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_students_reset_code'))
        batch_op.create_unique_constraint(None, ['reset_code'])

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount_cents',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
    
    # Custom CHECK constraints for ClassMembership
    # Using raw SQL to handle idempotency (IF NOT EXISTS pattern essentially)
    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'ck_membership_xor'
            ) THEN
                ALTER TABLE class_memberships ADD CONSTRAINT ck_membership_xor 
                CHECK (((admin_id IS NOT NULL AND student_id IS NULL) OR (admin_id IS NULL AND student_id IS NOT NULL)));
            END IF;
        END
        $$;
    """)

    op.execute("""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM pg_constraint
                WHERE conname = 'ck_membership_role_consistency'
            ) THEN
                ALTER TABLE class_memberships ADD CONSTRAINT ck_membership_role_consistency 
                CHECK (((admin_id IS NOT NULL AND role = 'admin') OR (student_id IS NOT NULL AND role = 'student')));
            END IF;
        END
        $$;
    """)


def downgrade():
    # Remove custom CHECK constraints
    op.execute("ALTER TABLE class_memberships DROP CONSTRAINT IF EXISTS ck_membership_role_consistency")
    op.execute("ALTER TABLE class_memberships DROP CONSTRAINT IF EXISTS ck_membership_xor")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('amount_cents',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('ix_students_reset_code'), ['reset_code'], unique=True)

    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.alter_column('teacher_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        batch_op.drop_index('ix_class_economies_status')

    with op.batch_alter_table('balance_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_balance_cache_scope'), ['join_code', 'student_id'], unique=False)

    # ### end Alembic commands ###
