"""Add announcement model

Revision ID: e3fbfe180e69
Revises: 64f0fdfc2079
Create Date: 2025-12-26 12:01:12.789314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3fbfe180e69'
down_revision = '64f0fdfc2079'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('join_code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['teacher_id'], ['admins.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_announcements_join_code'), ['join_code'], unique=False)
        batch_op.create_index('ix_announcements_join_code_active', ['join_code', 'is_active'], unique=False)
        batch_op.create_index('ix_announcements_teacher_join_code', ['teacher_id', 'join_code'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.drop_index('ix_announcements_teacher_join_code')
        batch_op.drop_index('ix_announcements_join_code_active')
        batch_op.drop_index(batch_op.f('ix_announcements_join_code'))

    op.drop_table('announcements')
    # ### end Alembic commands ###
