"""Refactor timezone handling

Revision ID: f3fe270c6f0e
Revises: 95107be9594c
Create Date: 2026-02-04 23:15:10.874181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# ============================================================================
# IDEMPOTENCY HELPERS (REQUIRED)
# ============================================================================

def table_exists(table_name):
    """Check if a table exists."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    return table_name in inspector.get_table_names()

def column_exists(table_name, column_name):
    """Check if a column exists in a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        columns = [col['name'] for col in inspector.get_columns(table_name)]
        return column_name in columns
    except Exception:
        return False

def index_exists(table_name, index_name):
    """Check if an index exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        indexes = [idx['name'] for idx in inspector.get_indexes(table_name)]
        return index_name in indexes
    except Exception:
        return False

def foreign_key_exists(table_name, fk_name):
    """Check if a foreign key exists on a table."""
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        fks = [fk['name'] for fk in inspector.get_foreign_keys(table_name)]
        return fk_name in fks
    except Exception:
        return False

def get_foreign_keys_by_column(table_name, column_name):
    """
    Get foreign key constraints that reference a specific column.
    
    Use this instead of hardcoding FK names in downgrade.
    """
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    try:
        return [
            fk for fk in inspector.get_foreign_keys(table_name)
            if column_name in fk['constrained_columns']
        ]
    except Exception:
        return []

# ============================================================================
# MIGRATION FUNCTIONS
# ============================================================================

# revision identifiers, used by Alembic.
revision = 'f3fe270c6f0e'
down_revision = '95107be9594c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('last_used',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('admin_invite_codes', schema=None) as batch_op:
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_login',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('tos_accepted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.alter_column('window_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('window_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('acknowledged_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('valid_until',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('analytics_alerts', 'fk_analytics_alerts_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_analytics_alerts_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.alter_column('event_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        if foreign_key_exists('analytics_events', 'fk_analytics_events_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_analytics_events_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.alter_column('window_start',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('window_end',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('computed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        if foreign_key_exists('analytics_snapshots', 'fk_analytics_snapshots_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_analytics_snapshots_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('announcements', 'fk_announcements_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_announcements_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.alter_column('interest_payout_start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('banking_settings', 'ix_banking_settings_join_code'):
            batch_op.drop_index(batch_op.f('ix_banking_settings_join_code'))
        if foreign_key_exists('banking_settings', 'banking_settings_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('banking_settings_join_code_fkey'), type_='foreignkey')
        if column_exists('banking_settings', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.alter_column('requested_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('demo_students', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('ended_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('feature_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('feature_settings', 'ix_feature_settings_join_code'):
            batch_op.drop_index(batch_op.f('ix_feature_settings_join_code'))
        if foreign_key_exists('feature_settings', 'feature_settings_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('feature_settings_join_code_fkey'), type_='foreignkey')
        if column_exists('feature_settings', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.alter_column('request_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('decision_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('left_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('return_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('hall_pass_logs', 'ix_hall_pass_logs_actor_membership_id'):
            batch_op.drop_index(batch_op.f('ix_hall_pass_logs_actor_membership_id'))
        if foreign_key_exists('hall_pass_logs', 'fk_hall_pass_logs_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_hall_pass_logs_join_code_class_economies'), type_='foreignkey')
        if foreign_key_exists('hall_pass_logs', 'hall_pass_logs_actor_membership_id_fkey'):
            batch_op.drop_constraint(batch_op.f('hall_pass_logs_actor_membership_id_fkey'), type_='foreignkey')
        if column_exists('hall_pass_logs', 'actor_membership_id'):
            batch_op.drop_column('actor_membership_id')

    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('hall_pass_settings', 'ix_hall_pass_settings_join_code'):
            batch_op.drop_index(batch_op.f('ix_hall_pass_settings_join_code'))
        if foreign_key_exists('hall_pass_settings', 'hall_pass_settings_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('hall_pass_settings_join_code_fkey'), type_='foreignkey')
        if column_exists('hall_pass_settings', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('incident_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('filed_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('processed_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('insurance_policies', 'ix_insurance_policies_join_code'):
            batch_op.drop_index(batch_op.f('ix_insurance_policies_join_code'))
        if foreign_key_exists('insurance_policies', 'insurance_policies_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('insurance_policies_join_code_fkey'), type_='foreignkey')
        if column_exists('insurance_policies', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('issue_categories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('issue_resolution_actions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('issue_status_history', schema=None) as batch_op:
        batch_op.alter_column('changed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('teacher_reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('teacher_resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('escalated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('sysadmin_reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('sysadmin_resolved_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('closed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('issues', 'fk_issues_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_issues_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('payroll_fines', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('payroll_fines', 'ix_payroll_fines_join_code'):
            batch_op.drop_index(batch_op.f('ix_payroll_fines_join_code'))
        if foreign_key_exists('payroll_fines', 'payroll_fines_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('payroll_fines_join_code_fkey'), type_='foreignkey')
        if column_exists('payroll_fines', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('payroll_rewards', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('payroll_rewards', 'ix_payroll_rewards_join_code'):
            batch_op.drop_index(batch_op.f('ix_payroll_rewards_join_code'))
        if foreign_key_exists('payroll_rewards', 'payroll_rewards_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('payroll_rewards_join_code_fkey'), type_='foreignkey')
        if column_exists('payroll_rewards', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.alter_column('next_payroll_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('first_pay_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('payroll_settings', 'ix_payroll_settings_join_code'):
            batch_op.drop_index(batch_op.f('ix_payroll_settings_join_code'))
        if foreign_key_exists('payroll_settings', 'payroll_settings_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('payroll_settings_join_code_fkey'), type_='foreignkey')
        if column_exists('payroll_settings', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('recovery_requests', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('expires_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('rent_items', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    # Safe addition of coverage columns with backfill
    if not column_exists('rent_payments', 'coverage_month'):
        op.add_column('rent_payments', sa.Column('coverage_month', sa.Integer(), nullable=True))
    if not column_exists('rent_payments', 'coverage_year'):
        op.add_column('rent_payments', sa.Column('coverage_year', sa.Integer(), nullable=True))
    
    # Backfill coverage fields from payment_date
    op.execute("""
        UPDATE rent_payments 
        SET 
            coverage_month = EXTRACT(MONTH FROM payment_date),
            coverage_year = EXTRACT(YEAR FROM payment_date)
        WHERE coverage_month IS NULL OR coverage_year IS NULL
    """)
    
    # Handle NULLs if payment_date was null (fallback to current date or 0 to satisfy NOT NULL)
    # Using 0/0 as fallback since nullable=False is required
    op.execute("""
        UPDATE rent_payments
        SET coverage_month = 1, coverage_year = 2026
        WHERE coverage_month IS NULL
    """)

    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        # Now safe to make nullable=False
        batch_op.alter_column('coverage_month', nullable=False)
        batch_op.alter_column('coverage_year', nullable=False)

        batch_op.alter_column('payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('rent_payments', 'fk_rent_payments_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_rent_payments_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.alter_column('first_rent_due_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('rent_settings', 'ix_rent_settings_join_code'):
            batch_op.drop_index(batch_op.f('ix_rent_settings_join_code'))
        if foreign_key_exists('rent_settings', 'rent_settings_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('rent_settings_join_code_fkey'), type_='foreignkey')
        if column_exists('rent_settings', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('rent_waivers', schema=None) as batch_op:
        batch_op.alter_column('waiver_start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('waiver_end_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.alter_column('auto_delist_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('store_items', 'ix_store_items_join_code'):
            batch_op.drop_index(batch_op.f('ix_store_items_join_code'))
        if foreign_key_exists('store_items', 'store_items_join_code_fkey'):
            batch_op.drop_constraint(batch_op.f('store_items_join_code_fkey'), type_='foreignkey')
        if column_exists('store_items', 'join_code'):
            batch_op.drop_column('join_code')

    with op.batch_alter_table('student_blocks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('student_blocks', 'fk_student_blocks_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_student_blocks_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('student_insurance', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('cancel_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_payment_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('next_payment_due',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('coverage_start_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('student_insurance', 'fk_student_insurance_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_student_insurance_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('student_items', schema=None) as batch_op:
        batch_op.alter_column('purchase_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('redemption_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('student_items', 'fk_student_items_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_student_items_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('student_recovery_codes', schema=None) as batch_op:
        batch_op.alter_column('verified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('notified_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('student_teachers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('insurance_last_paid',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('last_used',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('tap_events', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('tap_events', 'fk_tap_events_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_tap_events_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('teacher_blocks', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('claimed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if foreign_key_exists('teacher_blocks', 'fk_teacher_blocks_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_teacher_blocks_join_code_class_economies'), type_='foreignkey')

    with op.batch_alter_table('teacher_onboarding', schema=None) as batch_op:
        batch_op.alter_column('widget_dismissed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('completed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('skipped_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('last_activity_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('date_funds_available',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        if index_exists('transaction', 'ix_transaction_actor_membership_id'):
            batch_op.drop_index(batch_op.f('ix_transaction_actor_membership_id'))
        if foreign_key_exists('transaction', 'fk_transaction_join_code_class_economies'):
            batch_op.drop_constraint(batch_op.f('fk_transaction_join_code_class_economies'), type_='foreignkey')
        if foreign_key_exists('transaction', 'transaction_actor_membership_id_fkey'):
            batch_op.drop_constraint(batch_op.f('transaction_actor_membership_id_fkey'), type_='foreignkey')
        if column_exists('transaction', 'actor_membership_id'):
            batch_op.drop_column('actor_membership_id')

    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.alter_column('submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
        batch_op.alter_column('reviewed_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('reward_sent_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        if index_exists('class_memberships', 'ix_class_memberships_admin_id'):
            batch_op.drop_index(batch_op.f('ix_class_memberships_admin_id'))
        if index_exists('class_memberships', 'ix_class_memberships_admin_status'):
            batch_op.drop_index(batch_op.f('ix_class_memberships_admin_status'))
        if index_exists('class_memberships', 'ix_class_memberships_join_code'):
            batch_op.drop_index(batch_op.f('ix_class_memberships_join_code'))
        if index_exists('class_memberships', 'ix_class_memberships_join_code_role'):
            batch_op.drop_index(batch_op.f('ix_class_memberships_join_code_role'))
        if index_exists('class_memberships', 'ix_class_memberships_student_id'):
            batch_op.drop_index(batch_op.f('ix_class_memberships_student_id'))
        if index_exists('class_memberships', 'ix_class_memberships_student_status'):
            batch_op.drop_index(batch_op.f('ix_class_memberships_student_status'))

    if table_exists('class_memberships'):
        op.drop_table('class_memberships')
    with op.batch_alter_table('class_join_code_aliases', schema=None) as batch_op:
        if index_exists('class_join_code_aliases', 'ix_class_join_code_aliases_old_code'):
            batch_op.drop_index(batch_op.f('ix_class_join_code_aliases_old_code'))

    if table_exists('class_join_code_aliases'):
        op.drop_table('class_join_code_aliases')
    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        if index_exists('class_economies', 'ix_class_economies_created_by'):
            batch_op.drop_index(batch_op.f('ix_class_economies_created_by'))

    if table_exists('class_economies'):
        op.drop_table('class_economies')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_economies',
    sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('display_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('created_by_admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('archived_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admins.id'], name=op.f('class_economies_created_by_admin_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('join_code', name=op.f('class_economies_pkey'))
    )
    with op.batch_alter_table('class_economies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_economies_created_by'), ['created_by_admin_id'], unique=False)

    op.create_table('class_memberships',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('admin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admins.id'], name=op.f('class_memberships_admin_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['join_code'], ['class_economies.join_code'], name=op.f('class_memberships_join_code_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name=op.f('class_memberships_student_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('class_memberships_pkey')),
    sa.UniqueConstraint('join_code', 'admin_id', name=op.f('uq_class_membership_admin'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    sa.UniqueConstraint('join_code', 'student_id', name=op.f('uq_class_membership_student'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    with op.batch_alter_table('class_memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_memberships_student_status'), ['student_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_memberships_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_memberships_join_code_role'), ['join_code', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_memberships_join_code'), ['join_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_memberships_admin_status'), ['admin_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_class_memberships_admin_id'), ['admin_id'], unique=False)

    op.create_table('class_join_code_aliases',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('old_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('current_join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('rotated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['current_join_code'], ['class_economies.join_code'], name=op.f('class_join_code_aliases_current_join_code_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('class_join_code_aliases_pkey'))
    )
    with op.batch_alter_table('class_join_code_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_class_join_code_aliases_old_code'), ['old_code'], unique=True)
    with op.batch_alter_table('user_reports', schema=None) as batch_op:
        batch_op.alter_column('reward_sent_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_membership_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('transaction_actor_membership_id_fkey'), 'class_memberships', ['actor_membership_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_transaction_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_transaction_actor_membership_id'), ['actor_membership_id'], unique=False)
        batch_op.alter_column('date_funds_available',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('teacher_onboarding', schema=None) as batch_op:
        batch_op.alter_column('last_activity_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('skipped_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('started_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('widget_dismissed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('teacher_blocks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_teacher_blocks_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('claimed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('tap_events', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_tap_events_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('system_admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('last_used',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.alter_column('insurance_last_paid',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('student_teachers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('student_recovery_codes', schema=None) as batch_op:
        batch_op.alter_column('notified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('verified_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('student_items', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_student_items_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('redemption_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expiry_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('purchase_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('student_insurance', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_student_insurance_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('coverage_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('next_payment_due',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('cancel_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('purchase_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('student_blocks', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_student_blocks_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('store_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('store_items_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_store_items_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('auto_delist_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('rent_waivers', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('waiver_end_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('waiver_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('rent_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('rent_settings_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_rent_settings_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('first_rent_due_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('rent_payments', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_rent_payments_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        if column_exists('rent_payments', 'coverage_year'):
            batch_op.drop_column('coverage_year')
        if column_exists('rent_payments', 'coverage_month'):
            batch_op.drop_column('coverage_month')

    with op.batch_alter_table('rent_items', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('recovery_requests', schema=None) as batch_op:
        batch_op.alter_column('completed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('payroll_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('payroll_settings_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_payroll_settings_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('first_pay_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('next_payroll_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('payroll_rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('payroll_rewards_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_payroll_rewards_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('payroll_fines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('payroll_fines_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_payroll_fines_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('issues', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_issues_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('closed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('sysadmin_resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('sysadmin_reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('escalated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('teacher_resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('teacher_reviewed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('issue_status_history', schema=None) as batch_op:
        batch_op.alter_column('changed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('issue_resolution_actions', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('issue_categories', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('insurance_policies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('insurance_policies_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_insurance_policies_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('insurance_claims', schema=None) as batch_op:
        batch_op.alter_column('processed_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('filed_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('incident_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('hall_pass_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('hall_pass_settings_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_hall_pass_settings_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('hall_pass_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_membership_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('hall_pass_logs_actor_membership_id_fkey'), 'class_memberships', ['actor_membership_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('fk_hall_pass_logs_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_hall_pass_logs_actor_membership_id'), ['actor_membership_id'], unique=False)
        batch_op.alter_column('return_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('left_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('decision_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('request_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('feature_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('feature_settings_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_feature_settings_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('error_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('demo_students', schema=None) as batch_op:
        batch_op.alter_column('ended_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('deletion_requests', schema=None) as batch_op:
        batch_op.alter_column('resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('requested_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('banking_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('join_code', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('banking_settings_join_code_fkey'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.create_index(batch_op.f('ix_banking_settings_join_code'), ['join_code'], unique=False)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('interest_payout_start_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('announcements', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_announcements_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('analytics_snapshots', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_analytics_snapshots_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('computed_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('window_end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('window_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('analytics_events', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_analytics_events_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('event_date',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('analytics_alerts', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_analytics_alerts_join_code_class_economies'), 'class_economies', ['join_code'], ['join_code'], ondelete='CASCADE')
        batch_op.alter_column('valid_until',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('resolved_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('acknowledged_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('window_end',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
        batch_op.alter_column('window_start',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)

    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.alter_column('tos_accepted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('last_login',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('admin_invite_codes', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('expires_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)

    with op.batch_alter_table('admin_credentials', schema=None) as batch_op:
        batch_op.alter_column('last_used',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)



    # ### end Alembic commands ###
