name: Lint Workflows

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    paths:
      - ".github/workflows/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"

jobs:
  actionlint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: actionlint with reviewdog
        uses: reviewdog/action-actionlint@v1.70.0
        with:
          reporter: github-pr-check
          fail_level: error